### ISSUE TITLE
ES S3 repo backup rotation

### ISSUE THREAD

**Issue by panda87** [elastic/curator#689] opened 2016-07-13 17:22 UTC
Hi

I'm using ES 2.1.1 and curator 3.5.
In addition, im using curator as my auto increment cluster backup (cron job which running every hour)
I read today that ES doesn't reccomand using same repo for long time since the recovery will take longer than without snapshots.

The idea is to create weekly \ monthly repository and make snapshots until the next week \ month come and then rotate the S3 repository and create new (full) backup.

I see that for managing ES backup repos there is this tool: `es_repo_mgr` which will be added also to cron job.

My question is what is your recommendation for repo rotate and how can I set dynamic repo in the cron script?

Thanks
D.

**Comment by untergeek** [comment] 2016-07-20 15:26
> I read today that ES doesn't reccomand using same repo for long time since the recovery will take longer than without snapshots.

Please let me know where you read this.  I would like to see this recommendation in print, as it is not something we commonly recommend.  

Recovery only takes a long time when there are hundreds of thousands of segments.  This can easily be avoided by using a 2, or perhaps 3 tiered approach.  Frequent repository rollover should _not_ be necessary if this is handled correctly.  In fact, it can result in a lot of extra data storage cost, as data may be duplicated in multiple locations.

When using time-series data, we _do_ recommend having a "fast moving" snapshot repository.  This would have hourly or daily snapshots, but only persist them for a few days.  After your time-series indices rollover, they're unlikely to be changed, so you can do a "forceMerge," which is an optimize call in Curator 3.  It is recommended to forceMerge to 1 or 2 segments per shard, where feasible.  For snapshotting force merged segments, a separate repository would be recommended, because it only contains segments unlikely to change, so incremental segment creep wouldn't happen.

**Comment by untergeek** [comment] 2016-07-25 16:15
@panda87 can you please provide an update here?

**Comment by panda87** [comment] 2016-07-25 21:53
https://groups.google.com/forum/#!msg/elasticsearch/cXl9UrqgwBI/gEX0gSj2yqgJ

**Comment by untergeek** [comment] 2016-07-25 22:56
The only ES employees in that thread are Igor and myself, and the dates are two years ago.  The Elasticsearch google user group was deprecated some time ago, and migrated to https://discuss.elastic.co/c/elasticsearch, alongside forums for our other software.  That recommendation addresses a limited use case:

What Igor said:

> I would recommend pruning old snapshots as time goes by or starting snapshots into a new bucket/directory if you really need to maintain 2 hour resolution for 2 months old snapshots.

This is still true if you _"really need to maintain **2 hour resolution for 2 month old snapshots**."_  This is not common for any kind of time-series data (which I presume you're using, as you're using Curator for snapshots).  If you're using time-series data, or you do not need 2 hour resolution for 2 month old snapshots, there's a better way.

The slowness you're trying to avoid with lots of snapshots is actually a function of segment count.  

My comment in that referenced thread:

>Snapshots are at the segment level.  The more segments stored in the repository, the more segments will have to be compared to those in each successive snapshot.  With merges taking place continually in an active index, you may end up with a considerable number of "orphaned" segments stored in your repository, i.e. segments "backed up," but no longer directly correlating to a segment in your index.  Checking through these may be contributing to the increased amount of time between snapshots.  
>
>Consider pruning older snapshots.  "Orphaned" segments will be deleted, and any segments still referenced will be preserved.

A way to visualize what's constantly happening in indices with the Lucene segments is [here](http://blog.mikemccandless.com/2011/02/visualizing-lucenes-segment-merges.html), as demonstrated by one of our core Lucene committers.

A snapshot:

1. Prevents segment merges from happening until complete
2. Copies all segments as they were at snapshot initiation time to the shared file store
3. Associates the snapshot with the segments via pointers and metadata

The pointers point to the segments necessary to restore to a given point in time.  This becomes problematic when snapshots are taken at frequent intervals, or on time-series data.  Unchanged segments will not be re-copied, but with time-series indices, or frequently changing indices, these segments are constantly being updated by segment merges of new/changed data (as seen in the above video).  This means that there can be segments copied which _might_ contain duplicated data because the former segments have been merged one or more times, and are therefore considered a _new_ segment (the "old" segments which reference the same data are the "orphans" I'm talking about in my comment in that old thread).  _A single, daily index can easily have over 300 segments, before a forceMerge._

**The reason snapshots get slower over time is that each new segment to be snapshotted is compared to the other segments already stored in the repository.**  With more segments come more tests.  This does not scale.  Adding repositories _does_ solve this problem by reducing the number of segments in a single repository, but it should only be used, as Igor said, _"if you really need to maintain 2 hour resolution for 2 months old snapshots."_  Elasticsearch still needs to maintain a list of all repositories and all snapshots in them, so this greatly pads the amount of metadata that Elasticsearch has to track.

The best way to reduce segment creep with time-series indices is to use a tiered repository approach in combination with forceMerge.  For example:

* Tier 1 (hourly snapshots).
* Tier 2 (daily snapshots). 
* Tier 3 (weekly snapshots) _optional_

Each tier has its own repository.  The thinking is that Tier 1 only needs to persist for 48 to 72 hours (2 to 3 days).  By this time, a daily index rotation will have occurred, and you can forceMerge (optimize, in older versions of the API) segments per shard down to a small number, or even 1.  At this point, these optimized indices are ready to be snapshotted into tier 2.  This results in fewer segments to be compared 

Using Curator, you are able to perform all steps of this tiered approach.  It has the beauty of keeping a limited number of short-term snapshots in case a restore is immediately necessary, but a much larger number of long-term snapshots, _after they've been forceMerged,_ so that the number of segments in the repository—which is the cause of the slowness you're trying to avoid—is a non-issue.

**Comment by untergeek** [comment] 2016-07-26 22:30
@panda87 if this answers your question, please let me know, or close the ticket.

**Closed** 2016-08-02 14:47 UTC
Labels: question
