### ISSUE TITLE
es_repo_mgr missing in deb package curator-4.0.0

### ISSUE THREAD

**Issue by ksmets** [elastic/curator#675] opened 2016-07-01 18:10 UTC
Could you please include run_es_repo_mgr.py and es_repo_mgr.py in deb package?

**Comment by untergeek** [comment] 2016-07-01 18:56
Duplicate of #668 

Fixed in #670

**Comment by untergeek** [comment] 2016-07-01 18:56
I plan on releasing 4.0.1 today, if all goes well.

**Closed by untergeek** 2016-07-01 18:56 UTC
