### ISSUE TITLE
Curator filter removing indexes that ought to match

### ISSUE THREAD

**Issue by jhammerman79** [elastic/curator#889] opened 2017-02-17 19:50 UTC
Hello Curator maintainers,

On, curator version 4.1.2, we have a index_retention.yml file with the following content:
---
actions:
  1:
    action: delete_indices
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: log-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%-j'
      unit: days
      unit_count: 60
      exclude:
When we run curator with debug mode on, we get the attached output.
[curator_debug_output.zip](https://github.com/elastic/curator/files/784154/curator_debug_output.zip)

There are definitely indexes that should be matching, based on my understanding of the documentation.

Have I made a misconfiguration? I am happy to perform additional testing on our end to help identify the issue.

Thanks in advance for any assistance you can provide,
Joseph Hammerman

**Comment by untergeek** [comment] 2017-02-17 21:25
That would be because your timestring has an unsupported flag in it (`%-j`).  The supported flags are described [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_timestring.html).  `%j` is supported, but not `%-j`.  

_However..._

In #397, support for `%j` was added.  In #578, the regex map for `%j` was modified to support 1 to 3 digits, effectively making `%j` have a compatible regular expression to one for `%-j`.  I would try using `%j` instead.  I haven't had any follow-ups or complaints after the changes in #578, so I presume it should work for you.

Otherwise, I'd recommend using [`source: creation_date`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_source.html#_creation_date) or [`source: stats_result`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_source.html#_field_stats) instead of the index name.  

Also, you should update to the latest version of Curator, 4.2.6.

**Comment by untergeek** [comment] 2017-02-17 21:31
I don't know what's naming your indices, but for parsing's sake, I always advise using zero-padded numbers to avoid this kind of confusion.  Just my 2¢

**Comment by jhammerman79** [comment] 2017-02-21 15:00
Awesome, thanks!

**Comment by untergeek** [comment] 2017-02-21 16:02
Please close this with a follow-up if it works for you, @jhammerman79

**Comment by untergeek** [comment] 2017-02-25 00:10
Closing in expectation the issue is resolved.  Please re-open if this is not the case.

**Closed by untergeek** 2017-02-25 00:10 UTC
