### ISSUE TITLE
ERROR Schema error: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by samcro1967** [elastic/curator#1357] opened 2019-01-24 15:16 UTC
I am trying to delete indices from elasticsearch.

Running curator_cli --host localhost show_indices --verbose --header produces the following:

C:\Program Files\elasticsearch-curator>curator_cli --host localhost show_indices --verbose --header
Index               State     Size      Docs Pri Rep   Creation Timestamp
.kibana_1            open    5.2KB         1   1   0 2018-12-13T22:10:10Z
telegraf-2018.12.13  open  103.8MB   1105152   5   1 2018-12-13T22:09:42Z
telegraf-2018.12.14  open    1.5GB  16806115   5   1 2018-12-14T00:00:00Z
...

Running the following curator_cli --host localhost delete_indices --filter_list <back_slash>"'{"filtertype":"age","source":"name","timestring":"%Y.%m.%d","unit":"days","unit_count":30,"direction":"older"}<back_slash>" produces the following:

C:\Program Files\elasticsearch-curator>curator_cli --host localhost delete_indices --filter_list '\"'{"filtertype":"age","source":"name","timestring":"%Y.%m.%d","unit":"days","unit_count":1,"direction":"older"}'\"
2019-01-24 09:08:50,031 ERROR     Schema error: 'str' object has no attribute 'items'
2019-01-24 09:08:50,032 CRITICAL  Unable to parse filters: Configuration: filters: Location: show_indices singleton action "filters": Bad Value: "None", 'str' object has no attribute 'items'. Check configuration file.

I am encapsulating the filter type in quotes and escaping the outer quotes with back slashes.  Without doing that, I get invalid filter type error message I believe due to the Windows command line interpreter special characters.  I believe the correct filter type string is being passed to curator_cli.exe by doing this.

  - Version: elasticsearch-curator-5.6.0-amd64.msi
  - Platform: Microsoft Windows [Version 10.0.17134.523]

**Comment by untergeek** [comment] 2019-01-24 15:35
This is a known issue, and a duplicate of #1329

**Closed by untergeek** 2019-01-24 15:35 UTC

**Comment by samcro1967** [comment] 2019-01-24 16:43
Replacing the single quotes around the filtertype JSON and escaping the double quotes with a back slash inside the filtertype JSON seems to have worked.

C:\Program Files\elasticsearch-curator>curator_cli --host localhost show_indices --verbose --header --filter_list "{\"filtertype\":\"age\",\"source\":\"name\",\"timestring\":\"%Y.%m.%d\",\"unit\":\"days\",\"unit_count\":30,\"direction\":\"older\"}"
Index               State     Size      Docs Pri Rep   Creation Timestamp
telegraf-2018.12.13  open  103.8MB   1105152   5   1 2018-12-13T22:09:42Z
telegraf-2018.12.14  open    1.5GB  16806115   5   1 2018-12-14T00:00:00Z
telegraf-2018.12.15  open    1.5GB  17311397   5   1 2018-12-15T00:00:06Z
telegraf-2018.12.16  open    1.6GB  17499439   5   1 2018-12-16T00:00:08Z
telegraf-2018.12.17  open    1.6GB  17921179   5   1 2018-12-17T00:00:02Z
telegraf-2018.12.18  open    1.6GB  18098332   5   1 2018-12-18T00:00:06Z
telegraf-2018.12.19  open    1.6GB  18118504   5   1 2018-12-19T00:00:01Z
telegraf-2018.12.20  open    1.5GB  17397983   5   1 2018-12-20T00:00:04Z
telegraf-2018.12.21  open    1.3GB  16636635   5   1 2018-12-21T00:00:00Z
telegraf-2018.12.22  open    1.3GB  16824327   5   1 2018-12-22T00:00:05Z
telegraf-2018.12.23  open    1.3GB  17055585   5   1 2018-12-23T00:00:00Z
telegraf-2018.12.24  open    1.3GB  17043244   5   1 2018-12-24T00:00:03Z
telegraf-2018.12.25  open    1.1GB  14056419   5   1 2018-12-25T00:00:07Z

Switching to delete_indices seems to execute, but errored out.

C:\Program Files\elasticsearch-curator>curator_cli --host localhost delete_indices --filter_list "{\"filtertype\":\"age\",\"source\":\"name\",\"timestring\":\"%Y.%m.%d\",\"unit\":\"days\",\"unit_count\":30,\"direction\":\"older\"}"
2019-01-24 10:32:52,885 INFO      Deleting selected indices: ['telegraf-2018.12.23', 'telegraf-2018.12.13', 'telegraf-2018.12.25', 'telegraf-2018.12.18', 'telegraf-2018.12.20', 'telegraf-2018.12.19', 'telegraf-2018.12.22', 'telegraf-2018.12.16', 'telegraf-2018.12.21', 'telegraf-2018.12.17', 'telegraf-2018.12.14', 'telegraf-2018.12.15', 'telegraf-2018.12.24']
2019-01-24 10:32:52,885 INFO      ---deleting index telegraf-2018.12.23
2019-01-24 10:32:52,888 INFO      ---deleting index telegraf-2018.12.13
2019-01-24 10:32:52,889 INFO      ---deleting index telegraf-2018.12.25
2019-01-24 10:32:52,892 INFO      ---deleting index telegraf-2018.12.18
2019-01-24 10:32:52,892 INFO      ---deleting index telegraf-2018.12.20
2019-01-24 10:32:52,893 INFO      ---deleting index telegraf-2018.12.19
2019-01-24 10:32:52,894 INFO      ---deleting index telegraf-2018.12.22
2019-01-24 10:32:52,896 INFO      ---deleting index telegraf-2018.12.16
2019-01-24 10:32:52,896 INFO      ---deleting index telegraf-2018.12.21
2019-01-24 10:32:52,897 INFO      ---deleting index telegraf-2018.12.17
2019-01-24 10:32:52,901 INFO      ---deleting index telegraf-2018.12.14
2019-01-24 10:32:52,903 INFO      ---deleting index telegraf-2018.12.15
2019-01-24 10:32:52,904 INFO      ---deleting index telegraf-2018.12.24
2019-01-24 10:33:22,905 CRITICAL  Failed to complete action: delete_indices.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=30))

delete_indices appearsd to have partially worked.  I suspect this is a different issue and not related to MS DOS command line syntax errors.  When I rerun show_indicies, the same ones are listed, but there size is all zero now with the exception of one of them.

C:\Program Files\elasticsearch-curator>curator_cli --host localhost show_indices --verbose --header --filter_list "{\"filtertype\":\"age\",\"source\":\"name\",\"timestring\":\"%Y.%m.%d\",\"unit\":\"days\",\"unit_count\":30,\"direction\":\"older\"}"
Index               State   Size      Docs Pri Rep   Creation Timestamp
telegraf-2018.12.13  open   0.0B         0   5   1 2018-12-13T22:09:42Z
telegraf-2018.12.14  open   0.0B         0   5   1 2018-12-14T00:00:00Z
telegraf-2018.12.15  open   0.0B         0   5   1 2018-12-15T00:00:06Z
telegraf-2018.12.16  open   0.0B         0   5   1 2018-12-16T00:00:08Z
telegraf-2018.12.17  open  1.6GB  17921179   5   1 2018-12-17T00:00:02Z
telegraf-2018.12.18  open   0.0B         0   5   1 2018-12-18T00:00:06Z
telegraf-2018.12.19  open   0.0B         0   5   1 2018-12-19T00:00:01Z
telegraf-2018.12.20  open   0.0B         0   5   1 2018-12-20T00:00:04Z
telegraf-2018.12.21  open   0.0B         0   5   1 2018-12-21T00:00:00Z
telegraf-2018.12.22  open   0.0B         0   5   1 2018-12-22T00:00:05Z
telegraf-2018.12.23  open   0.0B         0   5   1 2018-12-23T00:00:00Z
telegraf-2018.12.24  open   0.0B         0   5   1 2018-12-24T00:00:03Z
telegraf-2018.12.25  open   0.0B         0   5   1 2018-12-25T00:00:07Z
