### ISSUE TITLE
curator_cli report KeyError: u'show-indices'

### ISSUE THREAD

**Issue by wwyhy** [elastic/curator#1309] opened 2018-11-06 14:51 UTC
when show the indices, i got there is no command "show-indices", but form the "curator_cli --help",
we can see the command. please help on this.

1. installed curator by pip
2. version: curator_cli, version 5.5.4
3. ```
# curator_cli --host x.x.x.x --port 9200 show-indices --verbose
2018-11-06 14:47:39,139 CRITICAL  Action must be one of ['snapshot', 'create_index', 'index_settings', 'rollover', 'forcemerge', 'cluster_routing', 'replicas', 'delete_indices', 'allocation', 'alias', 'restore', 'close', 'delete_snapshots', 'open', 'shrink', 'reindex']
Traceback (most recent call last):
  File "/bin/curator_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/curator/curator_cli.py", line 8, in main
    cli(obj={})
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/show.py", line 21, in show_indices
    action = cli_action(ctx.info_name, ctx.obj['config']['client'], {'allow_ilm_indices': allow_ilm_indices}, filter_list, ignore_empty_list)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/object_class.py", line 52, in __init__
    self.check_options(option_dict)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/object_class.py", line 103, in check_options
    options.get_schema(self.action),
  File "/usr/lib/python2.7/site-packages/curator/validators/options.py", line 144, in get_schema
    for each in action_specific(action):
  File "/usr/lib/python2.7/site-packages/curator/validators/options.py", line 129, in action_specific
    return options[action]
KeyError: u'show-indices'

```
4. 
```
# curator_cli --help
Usage: curator_cli [OPTIONS] COMMAND [ARGS]...

Options:
  --config PATH       Path to configuration file. Default: ~/.curator/curator.yml
  --host TEXT         Elasticsearch host.
  --url_prefix TEXT   Elasticsearch http url prefix.
  --port TEXT         Elasticsearch port.
  --use_ssl           Connect to Elasticsearch through SSL.
  --certificate TEXT  Path to certificate to use for SSL validation.
  --client-cert TEXT  Path to file containing SSL certificate for client auth.
  --client-key TEXT   Path to file containing SSL key for client auth.
  --ssl-no-validate   Do not validate SSL certificate
  --http_auth TEXT    Use Basic Authentication ex: user:pass
  --timeout INTEGER   Connection timeout in seconds.
  --master-only       Only operate on elected master node.
  --dry-run           Do not perform any changes.
  --loglevel TEXT     Log level
  --logfile TEXT      log file
  --logformat TEXT    Log output format [default|logstash|json].
  --version           Show the version and exit.
  --help              Show this message and exit.

Commands:
  alias             Add/Remove Indices to/from Alias
  allocation        Shard Routing Allocation
  close             Close Indices
  delete-indices    Delete Indices
  delete-snapshots  Delete Snapshots
  forcemerge        forceMerge Indices (reduce segment count)
  open              Open Indices
  replicas          Change Replica Count
  restore           Restore Indices
  rollover          Rollover Index associated with Alias
  show-indices      Show Indices
  show-snapshots    Show Snapshots
  shrink            Shrink Indices to --number_of_shards
  snapshot          Snapshot Indices
```

**Comment by untergeek** [comment] 2018-11-06 14:56
This is a duplicate of #1279 which was fixed in #1280.  The current workaround is to run
```
pip install -U click==6.7
```

**Closed by untergeek** 2018-11-06 14:56 UTC
