### ISSUE TITLE
ImportError: No module named _socket on Windows 64-bit

### ISSUE THREAD

**Issue by wespday** [elastic/curator#514] opened 2015-11-21 06:09 UTC
Getting this error in Curator 3.4.0 binary download on Windows (7 and Server 2012 64-bit) :
```
D:\apps\curator-3.4.0>curator.exe
Traceback (most recent call last):
  File "D:\apps\curator-3.4.0\run_curator.py", line 5, in <module>
  File "D:\apps\curator-3.4.0\curator\__init__.py", line 2, in curator
  File "D:\apps\curator-3.4.0\curator\api\__init__.py", line 1, in api
  File "D:\apps\curator-3.4.0\curator\api\utils.py", line 2, in utils
  File "D:\apps\curator-3.4.0\elasticsearch\__init__.py", line 17, in elasticsea
rch
  File "D:\apps\curator-3.4.0\elasticsearch\client\__init__.py", line 5, in clie
nt
  File "D:\apps\curator-3.4.0\elasticsearch\transport.py", line 5, in transport
  File "D:\apps\curator-3.4.0\elasticsearch\connection\__init__.py", line 2, in
connection
  File "D:\apps\curator-3.4.0\elasticsearch\connection\http_requests.py", line 1
1, in http_requests
  File "D:\apps\curator-3.4.0\elasticsearch\compat.py", line 7, in compat
  File "C:\Python27\lib\urllib.py", line 26, in <module>
  File "C:\Python27\lib\socket.py", line 47, in <module>
ImportError: No module named _socket
```

If I have Python installed at C:\Python27 it changes to this:
```
D:\apps\curator-3.4.0>curator.exe
Traceback (most recent call last):
  File "D:\apps\curator-3.4.0\run_curator.py", line 5, in <module>
  File "D:\apps\curator-3.4.0\curator\__init__.py", line 2, in curator
  File "D:\apps\curator-3.4.0\curator\api\__init__.py", line 1, in api
  File "D:\apps\curator-3.4.0\curator\api\utils.py", line 2, in utils
  File "D:\apps\curator-3.4.0\elasticsearch\__init__.py", line 17, in elasticsea
rch
  File "D:\apps\curator-3.4.0\elasticsearch\client\__init__.py", line 5, in clie
nt
  File "D:\apps\curator-3.4.0\elasticsearch\transport.py", line 5, in transport
  File "D:\apps\curator-3.4.0\elasticsearch\connection\__init__.py", line 2, in
connection
  File "D:\apps\curator-3.4.0\elasticsearch\connection\http_requests.py", line 1
1, in http_requests
  File "D:\apps\curator-3.4.0\elasticsearch\compat.py", line 7, in compat
  File "C:\Python27\lib\urllib.py", line 26, in <module>
    import socket
  File "C:\Python27\lib\socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd
```

**Comment by untergeek** [comment] 2015-11-21 16:26
Hmm. You should only see errors like this if there is a library conflict somewhere in your path. Everything in the zip package is self-contained and does not require _any_ Python to be installed. It tends to cause issues if you have Python (2.7 or 3.4) installed. 

Have you tried running from a Windows box with no Python on it?

**Comment by wespday** [comment] 2015-11-24 00:45
Yes, I've tried on a few boxes including a fresh VM now with the same result.

**Comment by untergeek** [comment] 2015-12-02 23:31
@wespday Sorry it's taken me so long to get back to you.  Building a Windows 7 VM and patching it fully, installing VisualStudio—and all other dependencies—is a fairly involved process.

Please test [this](https://dl.dropboxusercontent.com/u/1085030/curator-3.4.0-win64.zip) version here and let me know if you still have problems.  It was built, as mentioned, in Windows 7 64 bit, with Visual Studio 2013 Express (just the compiler part), the latest version of nuitka, and Python 2.7.10.

**Comment by hwwin** [comment] 2015-12-08 11:32
Hi, I'm facing the same problem. The patched build doesn't solve the problem. Tried it on different machines without any python installation present. The trace remains unchanged.

**Comment by untergeek** [comment] 2015-12-08 20:07
This is seriously strange.  What version of Windows are you using, @hwwin?

**Comment by bwinterseg** [comment] 2015-12-08 20:33
I'm having the same problem.  Windows server 2012 X64, no Python installed.

C:\temp\curator-3.4.0>curator --host 127.0.0.1 delete indices --older-than 30 --time-unit days timestring '%Y.%m.%d'

Traceback (most recent call last):
  File "C:\temp\curator-3.4.0\run_curator.py", line 5, in <module>
  File "C:\temp\curator-3.4.0\curator\__init__.py", line 2, in curator
  File "C:\temp\curator-3.4.0\curator\api\__init__.py", line 1, in api
  File "C:\temp\curator-3.4.0\curator\api\utils.py", line 2, in utils
  File "C:\temp\curator-3.4.0\elasticsearch\__init__.py", line 17, in elasticsearch
  File "C:\temp\curator-3.4.0\elasticsearch\client\__init__.py", line 5, in client
  File "C:\temp\curator-3.4.0\elasticsearch\transport.py", line 5, in transport
  File "C:\temp\curator-3.4.0\elasticsearch\connection\__init__.py", line 2, in connection
  File "C:\temp\curator-3.4.0\elasticsearch\connection\http_requests.py", line 11, in http_requests
  File "C:\temp\curator-3.4.0\elasticsearch\compat.py", line 7, in compat
  File "C:\Python27\lib\urllib.py", line 26, in <module>
  File "C:\Python27\lib\socket.py", line 47, in <module>
ImportError: No module named _socket

**Comment by hwwin** [comment] 2015-12-09 06:52
Tried it on Windows 7 Enterprise 64bit and Windows Server 2008 R2 Standard 64bit with SP1 installed. The error is identical in both instances.

**Comment by gschuager** [comment] 2015-12-31 12:50
Same problem here on Win 2012 x64 without Python

**Comment by samjudson** [comment] 2016-01-04 17:11
Same here. Windows Server 2012 R2, no Python, Curator 3.4.0.

**Comment by samjudson** [comment] 2016-01-04 21:41
I tried downloading version 3.3.0 and it contained a selection of .pyd files, including _socket.pyd.

I copied these PYD files to the 3.4.0 directory and I can now run curator. However I get a connection failure error when trying to run it, even when running on the same machine as elastic (default port etc).

Running the actual 3.3.0 files works (against 1.7.3, but fails against 2.1).

**Comment by untergeek** [comment] 2016-01-04 21:44
I'm sorry about the difficulty, everyone.  

I use Nuitka to compile the windows binary, and there's an actual issue with included files in recent versions (and I updated the ticket with my own results).  I'm rebuilding the binary right now with the last version of Python and Nuitka that made usable binaries.

**Comment by untergeek** [comment] 2016-01-04 22:50
@wespday @gschuager @hwwin @bwinterseg @samjudson please try [this version](https://dl.dropboxusercontent.com/u/1085030/curator-3.4.0-windows.zip).  It works for me on a python-less install—and bonus—should work on win32 _or_ win64.

**Comment by untergeek** [comment] 2016-01-04 22:50
I will publish this version if I get a few LGTMs.

**Comment by wespday** [comment] 2016-01-04 23:56
LGTM.  Thanks a bunch!

**Comment by samjudson** [comment] 2016-01-05 09:07
This now works against 1.7.3. and 2.1. I did notice however that the "--quiet" option doesn't seem to do anything?

**Comment by gschuager** [comment] 2016-01-05 11:47
LGTM. Thanks!

**Comment by hwwin** [comment] 2016-01-05 13:10
LGTM. Thanks @untergeek !

**Comment by untergeek** [comment] 2016-01-05 13:36
@samjudson The `--quiet` option is to prevent stdout messages when you have selected a log file via the `--logfile` option.  If you have not selected a log file, logging will continue to stdout, and `--quiet` will have no effect.

**Comment by samjudson** [comment] 2016-01-05 14:22
@untergeek Ah thanks, missed that bit in the docs. A LGTM here too then.

**Comment by dparkar** [comment] 2016-01-12 02:37
@untergeek There seems to be a small bug in the fixed version when you use --dry-run and if there is a timeout from elasticsearch :

2016-01-11 18:27:40,105 INFO      DRY RUN: delete: some-index-name-2015.12.13
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "run_curator.py", line 8, in <module>
  File "curator\curator.py", line 5, in main
  File "C:\Python27\lib\site-packages\click\core.py", line 716, in __call__
  File "C:\Python27\lib\site-packages\click\core.py", line 696, in main
  File "C:\Python27\lib\site-packages\click\core.py", line 1060, in invoke
  File "C:\Python27\lib\site-packages\click\core.py", line 1060, in invoke
  File "C:\Python27\lib\site-packages\click\core.py", line 889, in invoke
  File "C:\Python27\lib\site-packages\click\core.py", line 534, in invoke
  File "C:\Python27\lib\site-packages\click\decorators.py", line 17, in new_func
  File "curator\cli\index_selection.py", line 152, in indices
  File "curator\cli\utils.py", line 79, in show_dry_run
  File "curator\api\utils.py", line 96, in index_closed
  File "C:\Python27\lib\site-packages\elasticsearch\client\utils.py", line 69, in _wrapped
  File "C:\Python27\lib\site-packages\elasticsearch\client\cat.py", line 119, in indices
  File "C:\Python27\lib\site-packages\elasticsearch\transport.py", line 307, in perform_request
  File "C:\Python27\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 86, in perform_request
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'somehost', port=81): Read timed out. (read timeout=30))

**Comment by untergeek** [comment] 2016-01-12 03:41
@dparkar, did you set a higher timeout?  `--dry-run` isn't likely to increase timeouts if that's needed.  And it appears that you have a full 30 second timeout (and 30 seconds is the default).

**Comment by untergeek** [comment] 2016-01-12 03:48
@dparkar Yes, `--dry-run` is different: https://github.com/elastic/curator/blob/master/curator/cli/index_selection.py#L151-L152

and

https://github.com/elastic/curator/blob/master/curator/cli/utils.py#L72-L81

It you're having 30 second timeouts in the `show_dry_run` method, that's a problem.  It implies that it's taking more than 30 seconds to check if a single index is closed.  I'm not sure what's going on in your cluster, but that's indicative of either a huge number of indices (which is addressed in 59bbf8a), or perhaps an overburdened cluster.

**Comment by dparkar** [comment] 2016-01-12 23:19
@untergeek Thanks for the confirmation. The cluster issue was expected as I was going through a deployment. I assumed that dry-run follows exactly the same steps as the real run except actually modifying the cluster.

**Comment by styfle** [comment] 2016-02-08 18:16
I downloaded version 3.4.0 from the [installation guide link](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html#windows-binary) today and got the same `ImportError: No module named _socket` as the OP.

However the Dropbox link in [issuecomment-168836720](#issuecomment-168836720) seems to work for me. LGTM :+1: 

@untergeek Should the installation link on the elastic website be updated?

**Comment by untergeek** [comment] 2016-02-08 20:53
@styfle Thanks for reporting back.

I'm actually finishing up a new release in the next few days.  The new release will include new instructions because I'm including an MSI for Windows, and instructions on how to build your own binary, if necessary.

**Comment by MonDeveloper** [comment] 2016-02-09 20:56
Same problem here Win Srv 2012 R2 - No Pyton.
Dropbox link seems broken tonight from Italy

**Comment by untergeek** [comment] 2016-02-09 21:05
@MonDeveloper Please hold on a few more hours.  I'm trying to release an update.

**Comment by untergeek** [comment] 2016-02-11 00:31
Thank you all for your patience.  3.4.1 is released, and the Windows download has been updated.  Please see [the docs](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html#windows-binary).

**Closed by untergeek** 2016-02-11 00:31 UTC

**Comment by styfle** [comment] 2016-02-11 21:47
@untergeek Thanks!
Any reason why the link was changed from win64 to win32?

**Comment by untergeek** [comment] 2016-02-11 21:58
Because it's a 32bit binary now.  I switched from using [nuitka](http://nuitka.net) to using [cx_Freeze](http://cx-freeze.readthedocs.org/en/latest/index.html) to generate the binaries (and now, MSI).
