### ISSUE TITLE
continue_if_exception is not continuing if an exception occurs

### ISSUE THREAD

**Issue by PeterGrace** [elastic/curator#879] opened 2017-02-06 15:58 UTC
I have continue_if_exception set to True in my yaml, however curator still closes after action 1 instead of moving forward to subsequent actions.  See log and config below.  Am I misunderstanding how continue_if_exception is supposed to work?

```
2017-02-06 15:57:35,322 INFO      Preparing Action ID: 1, "delete_snapshots"
2017-02-06 15:57:35,336 INFO      Trying Action ID: 1, "delete_snapshots": delete 1 snapshot taken over 20 days ago
2017-02-06 15:57:35,380 ERROR     Unable to complete action "delete_snapshots".  No actionable items in list: <class 'curator.exceptions.NoSnapshots'>
```

Config:

```
actions:
  1:
    action: delete_snapshots
    description: "delete 1 snapshot taken over 20 days ago"
    options:
      repository: "itbackups"
      continue_if_exception: True
      disable_action: False
      timeout_override: 300
    filters:
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 20
      - filtertype: count
        count: 1
        exclude: False
  2:
    action: snapshot
    description: "snapshot 1 index over 45 days old"
    options:
       ... <snipped for brevity>
```

**Comment by untergeek** [comment] 2017-02-06 16:06
This is a duplicate of #831 

You need the `ignore_empty_list` option .  There are two kinds of exceptions:

1. **Something failed with either Curator or Elasticsearch.** This is covered by the `continue_if_exception` option.
2. **The list to act on is empty.** This is covered by the `ignore_empty_list` option.

The reason these are separate is that there are cases where an empty list will occur, but it shouldn't be treated as a regular exception.  Because Curator can catch an empty list as a separate exception, it won't accidentally continue if a type 1 exception was the cause (because in such a case, you wouldn't normally want it to continue).  

Empty list conditions can occur when you first start using Curator.  You might want to purge indices older than 30 days, but you only have 3 or 4 right now.  This would trigger the exception above, but it's not really an error.  This is why the separate `ignore_empty_list` option exists.

**Closed by untergeek** 2017-02-06 16:06 UTC
