### ISSUE TITLE
Curator 3.0.3 doesn't list the indices that it is deleting

### ISSUE THREAD

**Issue by brian-from-fl** [elastic/curator#375] opened 2015-05-20 22:03 UTC
I have an issue with curator 3.0.3. It won't show the indices that it deletes like the old 1.2.2 version did. Here is the output from two runs, both using the --logfile option to direct the logs to an on-disk file.

When I use the --dry-run option, logstash does indeed list the indices that would be deleted (in this case, only one):

    2015-05-20 15:01:19,290 INFO      Job starting: delete indices
    2015-05-20 15:01:19,314 INFO      Pruning Kibana-related indices to prevent accidental deletion.
    2015-05-20 15:01:19,314 INFO      DRY RUN MODE.  No changes will be made.
    2015-05-20 15:01:19,314 INFO      DRY RUN: delete: logstash-2015.05.14

When the --dry-run option is omitted, the index is deleted but it is not shown in the log:

    2015-05-20 15:02:24,123 INFO      Job starting: delete indices
    2015-05-20 15:02:24,136 INFO      Pruning Kibana-related indices to prevent accidental deletion.
    2015-05-20 15:02:24,152 INFO      Job completed successfully.

A quick check with Elasticsearch Head confirms that the logstash-2015.05.14 index was in fact truly deleted.

**Comment by untergeek** [comment] 2015-05-20 22:28
Duplicate of #372

**Closed by untergeek** 2015-05-20 22:28 UTC
