### ISSUE TITLE
Curator rollover documentation does not match Elasticsearch rollover API documentation

### ISSUE THREAD

**Issue by dustin-decker** [elastic/curator#1144] opened 2018-02-14 16:42 UTC
### Expected Behavior
Curator should have similar controls and behavior as Elasticsearch API

### Actual Behavior
*curator*
When choosing conditions, either one of max_age or max_docs, or both may be used. If both are used, then both conditions must be matched for the rollover to occur.
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/rollover.html

*elasticsearch*
Elasticsearch also supports `max_size`, and will rollover if *ANY* condition of the three possible conditions is met.

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-rollover-index.html#CO150-2

**Comment by untergeek** [comment] 2018-02-14 16:54
Duplicate of #1140

**Comment by dustin-decker** [comment] 2018-02-25 23:57
That issue does not capture this difference:
- curator will rollover if ALL conditions match
- elasticsearch will rollover if ANY conditions match

According to the curator docs, at least. I have not verified the behavior.

**Comment by untergeek** [comment] 2018-02-26 00:18
I will have to confirm.  I was initially informed it was an _AND,_ but the Elasticsearch documentation does appear to be an _OR._

Curator only passes the arguments along, so it will be a matter of correcting the docs is all, should the _OR_ be the correct interpretation.

**Comment by untergeek** [comment] 2018-03-06 03:27
Fixed in #1140

**Closed by untergeek** 2018-03-06 03:27 UTC
