### ISSUE TITLE
force-merge  action status

### ISSUE THREAD

**Issue by Strijd** [elastic/curator#969] opened 2017-05-17 13:04 UTC
index:24.G
curator: 5.0.4

action.yml 
```
actions:
  1:
    action: forcemerge
    description: forcem and mergem
    options:
      max_num_segments: 1
      delay: 10
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: index_
  2:
    action: delete_snapshots
    description: "Delete force-merge snapshot"
    options:
      repository: force-merge
      retry_interval: 10
      retry_count: 10
    filters:
    - filtertype: pattern
      kind: prefix
      value: force-
  3:
    action: snapshot
    description: snaphot after force-merge
    options:
      repository: force-merge
      name: force-merge
      wait_for_completion: True
      max_wait: 3600
      wait_interval: 10
      ignore_unavailable: False
      include_global_state: False
      partial: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: index_

```
While issuing the command : 
```
GET http://x.x.x.7:9200/_snapshot/force-merge/force-merge
```
Retrieves the correct status 
```
{
   "snapshots": [
      {
         "snapshot": "force-merge",
         "uuid": "QCC4LA7bT5igbPIAfa2FZA",
         "version_id": 5010199,
         "version": "5.1.1",
         "indices": [
            "index_v0.2_2017-05-16_270b7c8edcc74744b39bbf304753b06e"
         ],
         "state": "SUCCESS",
         "start_time": "2017-05-17T11:58:17.303Z",
         "start_time_in_millis": 1495022297303,
         "end_time": "2017-05-17T12:08:05.719Z",
         "end_time_in_millis": 1495022885719,
         "duration_in_millis": 588416,
         "failures": [],
         "shards": {
            "total": 8,
            "failed": 0,
            "successful": 8
         }
      }
   ]
}
```
curators logs shows otherwise, an the job is stuck 
```
2017-05-17 12:28:30,309 INFO      GET http://x.x.x7:9200/_nodes/_local [status:200 request:0.002s]
2017-05-17 12:28:30,311 INFO      GET http://x.x.x7:9200/_cluster/state/master_node [status:200 request:0.001s]
2017-05-17 12:28:30,311 INFO      Trying Action ID: 1, "forcemerge": forcem and mergem
2017-05-17 12:28:30,313 INFO      GET http://x.x.x7:9200/_all/_settings?expand_wildcards=open%2Cclosed [status:200 request:0.001s]
2017-05-17 12:28:30,314 INFO      GET http://x.x.x7:9200/ [status:200 request:0.001s]
2017-05-17 12:28:30,332 INFO      GET http://x.x.x7:9200/_cluster/state/metadata/indexv0.2_2017-05-16_270b7c8edcc74744b39bbf304753b06e [status:200 request:0.018s]
2017-05-17 12:28:30,336 INFO      GET http://x.x.x7:9200/indexv0.2_2017-05-16_270b7c8edcc74744b39bbf304753b06e/_stats/store,docs [status:200 request:0.002s]
2017-05-17 12:28:30,400 INFO      GET http://x.x.x7:9200/indexv0.2_2017-05-16_270b7c8edcc74744b39bbf304753b06e/_segments [status:200 request:0.063s]
2017-05-17 12:28:30,402 INFO      forceMerging selected indices
2017-05-17 12:28:30,402 INFO      forceMerging index indexv0.2_2017-05-16_270b7c8edcc74744b39bbf304753b06e to 1 segments per shard.  Please wait..
```

**Comment by Strijd** [comment] 2017-05-17 13:05
update with debug soon

**Comment by untergeek** [comment] 2017-05-17 14:08
What you're reporting is actually expected behavior.

```
2017-05-17 13:02:46,662 INFO      POST http://x.x.x.7:9200/index_v0.2_2017-05-16_270b7c8edcc74744b39bbf304753b06e/_forcemerge?max_num_segments=1 [status:200 request:2056.259s]
```
So, it took 2056 seconds to finish the forceMerge.  That's not unexpected.  Curator [automatically increases the default client timeout when performing snapshot, restore, and forceMerge actions](https://github.com/elastic/curator/blob/v5.0.4/curator/defaults/option_defaults.py#L214-L224).  It does not do so, however, when performing the other actions (except for that tiny bump for close actions, since it tries to do a synced_flush).

```
2017-05-17 13:03:26,934 WARNING   DELETE http://x.x.x.7:9200/_snapshot/force-merge/force-merge [status:N/A request:30.031s]
```
and
```
ReadTimeoutError: HTTPConnectionPool(host=u'x.x.x.7', port=9200): Read timed out. (read timeout=30)
```

Curator's default client timeout is 30 seconds.  Even with 
```
      retry_interval: 10
      retry_count: 10
```
...Curator will not ever retry if a client times out before it will attempt a retry after failure.

You'll have to either change the value of [`timeout`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.0/configfile.html#timeout) in your client YAML file, or set a [`timeout_override`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.0/option_timeout_override.html) in the action file in the options section for the `delete_snapshots` action.

It should be noted that the snapshot delete operation is still happening behind the scenes in the cluster.  Curator just doesn't get to see the end of the operation if the client times out before it's over.

**Comment by untergeek** [comment] 2017-05-19 23:29
Since this appears to be a non-issue, I'm closing this.  Feel free to re-open if you feel that more discussion is needed.

**Closed by untergeek** 2017-05-19 23:29 UTC
Labels: Issue Resolved
