### ISSUE TITLE
Filter Element timestring can substring match incorrectly:  example %Y.%W matches %Y.%m%.d

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/curator#707] opened 2016-07-27 14:22 UTC
During configuration of curator with multiple types of timestamped index names we encountered a case in which the timestring of %Y.%W would unexpectedly match an index with a %Y.%m.%d timestring.  Is it possible to add an anchor or option for an anchor to the timestring regex to more accurately match in these cases?

**Comment by untergeek** [comment] 2016-07-27 14:56
The answer is just to employ another filter.  You can exclude a `pattern` `filtertype` with a `value` of `'%Y.%m.%d'`:

```
    - filtertype: pattern
      kind: timestring
      value: '%Y.%m.%d'
      exclude: True
```

This filter should work anywhere in the chain, but it might be easier to visualize if it appears _before_ the age filter with the weekly timestring.

**Comment by untergeek** [comment] 2016-08-01 20:35
Since there's a simple fix for this, I'm going to mark it complete.  If you believe this is in error, please feel free to reopen this with a comment as to why, or open another ticket.

**Comment by jakommo** [comment] 2016-12-29 10:43
I hit this today with the following config:

```
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%W'
      unit: weeks
      unit_count: 2
```

and adding an exclude filter solved it.

```
    filters:
    - filtertype: pattern
      kind: timestring
      value: '%Y.%m.%d'
      exclude: True
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%W'
      unit: weeks
      unit_count: 2
```

While there is a workaround, it sounds like a bug to me. `'%Y.%W'` should not match indices with `'%Y.%m.%d'`.
@untergeek are you open for discussion on this one? 

I'm curious to understand why this happens. Is `'%Y.%W'` translated to a regexp without an `$` at the end?

**Comment by untergeek** [comment] 2016-12-29 17:02
@jakommo the problem is that dates do not always appear at the end of an index name.  While it is very common for that to be the case, I have also seen `2016.12.29-suffix`, and `prod-2016.12.29-logtype` and other variations.  As a result, the regexes that match dates are all preceded and followed by `.*`.  So, for example, the year-month-day regex is `^.*\d{4}\.\d{2}\.\d{2}.*$`.  

This is why you need a second filter to prevent year-month-day indices if you only want year-week.  While it may be possible to write in an implied filter blocking year-month-day indices, I'm not sure I like the implications of an invisible filter.  I'd rather instruct users with the _why_ and the _how_ of working around it.

**Comment by jakommo** [comment] 2016-12-29 17:25
Thanks for the explanation, I didn't think about the "date somewhere else then the end of the index name" cases.

**Closed by jakommo** 2016-12-29 17:25 UTC
