### ISSUE TITLE
Schema errors, likely due to new version of voluptuous 

### ISSUE THREAD

**Issue by woodlee** [elastic/curator#1149] opened 2018-02-15 15:44 UTC
### Expected Behavior
No errors when executing a rollover.

### Actual Behavior
```
2018-02-15 15:26:57,330 ERROR     Schema error: expected str for dictionary value @ data['new_index']
Traceback (most recent call last):
  File "venv/lib/python3.5/site-packages/curator/validators/schemacheck.py", line 57, in result
    return self.schema(self.config)
  File "venv/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "venv/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 587, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "venv/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 425, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['new_index']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/bin/curator", line 11, in <module>
    sys.exit(cli())
  File "venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "venv/lib/python3.5/site-packages/curator/cli.py", line 211, in cli
    run(config, action_file, dry_run)
  File "venv/lib/python3.5/site-packages/curator/cli.py", line 119, in run
    action_dict = validate_actions(action_config)
  File "venv/lib/python3.5/site-packages/curator/utils.py", line 1418, in validate_actions
    loc
  File "venv/lib/python3.5/site-packages/curator/validators/schemacheck.py", line 68, in result
    self.test_what, self.location, self.badvalue, self.error)
curator.exceptions.ConfigurationError: Configuration: options: Location: Action ID "2", action "rollover": Bad Value: "(could not determine)", expected str for dictionary value @ data['new_index']. Check configuration file.
```

### Steps to Reproduce the Problem
Run Curator with an action step configured like so:
```
  1:
    action: rollover
    description: Rollover my alias
    options:
      name: my_alias
      conditions:
        max_docs: 13000000  
```
### Specifications

  - Version: 5.4.1
  - Platform: Python 3.5.2 on Ubuntu 16.04

## Context (Environment)
The issue has halted our nightly execution of Curator to rollover some indices (among other tasks).

## Detailed Description
Curator v5.4.1 began throwing a new ConfigurationError for me last night despite no changes in our configuration. After some investigation, I think this may be related to the recent release of a new version of Voluptuous. We run Curator on a CI server, and the job rebuilds the virtualenv on each run. Since Curator doesn't explicitly pin the Voluptuous version, the behavior changed with the new release. I am not certain whether the fix ought to be in Curator or Voluptuous but figured it couldn't hurt to open here.

A potential solution might be to have `setup.py` explicitly pin the prior version of Voluptuous, but there's probably something better.

**Comment by untergeek** [comment] 2018-02-15 16:40
What you have shared for the steps to reproduce the problem is not what you are using.

The error identifies `Action ID "2"`, and the dictionary value `new_index` does not appear anywhere in the supplied config.

Please share exactly what you have, so I can duplicate it, or share the error generated by the supplied configuration.

**Comment by untergeek** [comment] 2018-02-15 16:42
By way of comparison, my own CI (Travis) tests with Voluptuous 0.10.5 and that works across python versions 2.7, 3.4, 3.5, and 3.6.

**Comment by woodlee** [comment] 2018-02-15 16:55
@untergeek Yep, was just trying to clean things up for conciseness. The real file starts like so:
```
actions:
  1:
    action: snapshot
    description: Snapshot production request event indices
    options:
      repository: s3_snapshot_repository
      name: prod_request_event_v1-%Y%m%d%H%M%S
    filters:
    - filtertype: alias
      aliases: prod_request_event_v1
  2:
    action: rollover
    description: Rollover large request event indices (prod)
    options:
      name: prod_request_event_v1_writes
      conditions:
        max_docs: 13000000  # Targeting 10GB/shard
  3:
<...several other actions...>
```
Everything was working fine for us as well on Voluptuous 0.10.5, but sometime in the past 24 hours they published a new version 0.11.1 to PyPI which I believe to be the issue. I intend to verify this soon by pinning the Voluptuous version in our own local pip requirements, but am having to wait for another cluster maintenance task to finish first.

**Comment by untergeek** [comment] 2018-02-15 21:38
Will look into it.  My current CI builds report 10 failures, and all of them are schema related.

**Comment by woodlee** [comment] 2018-02-15 23:58
I can confirm that pinning the version of Voluptuous to 0.10.5 in our local virtualenv resolves the issue.

**Comment by matthagenbuch** [comment] 2018-02-19 15:29
+1 regarding volutpuous==0.10.5

**Comment by baddogdown** [comment] 2018-02-27 13:33
+1 getting this issue.

**Comment by untergeek** [comment] 2018-03-04 19:43
This is fixed by way of #1156

**Closed by untergeek** 2018-03-04 19:43 UTC

**Comment by nguyening** [comment] 2018-03-05 19:54
@untergeek - is there going to be an associated release?

**Comment by untergeek** [comment] 2018-03-05 20:49
Yes. Should be within a week or two. I have a few more bugs to squash before I make a new release.
