### ISSUE TITLE
Adding an option to set index.merge.scheduler.max_thread_count 

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/curator#847] opened 2016-12-20 10:18 UTC
A common case for Curator is to move indices from Hot nodes to Warm nodes. A common scenario is that the Hot nodes are backed by SSD disks and the Warm nodes are backed by spinning disks. For spinning disks, it is recommended to have the option `index.merge.scheduler.max_thread_count` set to 1.
This parameter in version 5 is an index level parameter, only dynamically settable - when trying to set it in the yml files, the following error happens: 
```
Since elasticsearch 5.x index level settings can NOT be set on the nodes
configuration like the elasticsearch.yaml, in system properties or command line
arguments.In order to upgrade all indices the settings must be updated via the
/${index}/_settings API. Unless all settings are dynamic all indices must be closed
in order to apply the upgradeIndices created in the future should use index templates
to set default values. 
```

It would be great to be able to configure this parameter, so in the Hot(ssd)-Warm(spinning) architecture it can be tuned to have the optimal value in the warm nodes.

**Comment by untergeek** [comment] 2017-03-27 19:57
Have you tried setting this in the `extra_settings` option for the allocation action?  Just a thought.

**Comment by untergeek** [comment] 2017-03-27 21:32
Duplicate of #656

**Closed by untergeek** 2017-03-27 21:32 UTC
Labels: feature_request
