### ISSUE TITLE
Error when no indices were deleted

### ISSUE THREAD

**Issue by odolbeau** [elastic/curator#391] opened 2015-06-02 13:43 UTC
Hi all,

Is it normal that curator return an error when a valid command doesn't do anything?
For example:
```
/usr/local/bin/curator --loglevel WARN delete indices --older-than 6 --time-unit days --timestring %Y.%m.%d --prefix "foobar"
```
This command will return 0 if (at least) 1 indice is deleted. But it will return 99 if no indice is deleted.

I've just checked, it's not the behaviour of the old version.

It's a bit problematic when curator is used in a cron.
If, for a given reason, an indice is deleted manually, an email will be sent because logstash will fail.

**Comment by untergeek** [comment] 2015-06-02 17:18
I appreciate your problem.  I will probably remove exit code `99` in 3.1.1 or 3.2.0.  Closing this as it's a duplicate of #371

**Closed by untergeek** 2015-06-02 17:18 UTC
