### ISSUE TITLE
Feature Request: Add Readonly option for indexes

### ISSUE THREAD

**Issue by cembree** [elastic/curator#360] opened 2015-04-21 18:41 UTC
We have found that it is beneficial, in some cases, to set older indexes to Read Only to reduce overhead in our clusters.  Our use case is billions of documents per hour in hourly partitioned indexes.   Index Commands used:

indexname/_settings" -d ' { "index" : { "blocks.write" : "true", "codec.bloom.load" : "false" } }'

**Comment by untergeek** [comment] 2015-04-21 18:52
Part of the reason you may be having read issues with your indices is that they're hourly.  Elasticsearch automatically "times out" an index after 30 minutes, reclaiming the resources allocated to "active" indices.  This would leave a decent chunk of memory unavailable for 30 minutes of the next index's hour.  That said, how do you know you've reduced overhead by setting indices to read-only? 

This feature has been requested before, so this is actually a duplicate of #160 

It is, maybe, perhaps, finally time to add the feature.   I am reluctant to do so because there will be those who set recent indices to read-only and blow-up their Logstash instances because old data sometimes straggles in from the past.  This will cause errors and all kinds of _fun_ as Elasticsearch pushes back and says it can't write to that index.

I will close this issue shortly, as all other discussion should be on #160

**Closed** 2015-04-21 19:47 UTC
Labels: duplicate
