### ISSUE TITLE
AWS Elasticsearch version 5.x support?

### ISSUE THREAD

**Issue by xamox** [elastic/curator#880] opened 2017-02-07 01:25 UTC
AWS just released their Elasticsearch service last week (https://aws.amazon.com/about-aws/whats-new/2017/01/elasticsearch-5-now-available-on-amazon-elasticsearch-service/).   It seems like curator works with AWS but version 4 doesn't appear to work with AWS ES v2.x, will version 4 support AWS ES v5.x?

**Comment by untergeek** [comment] 2017-02-07 01:28
See the [version compatibility matrix](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/version-compatibility.html).

As it appears that AWS ES now supports the /_cluster/state endpoint, it _should_ work with Curator.

**Comment by xamox** [comment] 2017-02-07 01:32
@untergeek Thanks for the quick feedback.  Okay, I'll give it a test run and see how it goes.

**Comment by volcomism** [comment] 2017-02-08 15:47
I run into the following issue when trying to connect to an ES cluster (v5.1.2) hosted by AWS. Running this locally against the same ES version, works fine. Has anyone else been able to get this working?

Version 4.2.6

Command: 
```
curator_cli --logfile ./curator.log --loglevel INFO --logformat default --host aws-elasticsearch-domain --port 80 delete_indices --filter_list '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":13},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/curator_cli", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.4', 'console_scripts', 'curator_cli')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/singletons.py", line 267, in delete_indices_singleton
    ilo = IndexList(client)
  File "/usr/local/lib/python2.7/dist-packages/curator/indexlist.py", line 31, in __init__
    self.__get_indices()
  File "/usr/local/lib/python2.7/dist-packages/curator/indexlist.py", line 71, in __get_indices
    self._get_metadata()
  File "/usr/local/lib/python2.7/dist-packages/curator/indexlist.py", line 158, in _get_metadata
    if not 'creation_date' in wl['settings']['index']:
KeyError: 'settings'
```

**Comment by untergeek** [comment] 2017-02-08 16:27
Interesting.  I wonder what AWS included in the metadata.  They apparently included the `/_cluster/state` endpoint, which is necessary for Curator, but may not have included all of the necessary information _in_ that endpoint.  It does not appear that the individual index settings (which contain the metadata) are there, at least not under the `settings` key.

I'd love it if you could run with `--loglevel DEBUG` and attach the resulting output (after sanitizing anything sensitive).

As a side note, are you 100% sure you have 4.2.6?  It looks like you have 4.2.4 from the traceback output:

```
load_entry_point('elasticsearch-curator==4.2.4', 'console_scripts', 'curator_cli')()
```

You can tell by running `curator --version`.  It does look like you installed via pip, as you're running with Python 2.7.

**Comment by volcomism** [comment] 2017-02-09 08:59
I seem to receive the same traceback when using `--loglevel DEBUG`.

Sorry for the confusion regarding versions, I was running 4.2.6 but had rolled back temporarily to 4.2.4 to troubleshoot and pasted the previous traceback. The traceback below comes from 4.2.6.
```
Traceback (most recent call last):
  File "/usr/local/bin/curator_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/singletons.py", line 266, in delete_indices_singleton
    ilo = IndexList(client)
  File "/usr/local/lib/python2.7/dist-packages/curator/indexlist.py", line 31, in __init__
    self.__get_indices()
  File "/usr/local/lib/python2.7/dist-packages/curator/indexlist.py", line 71, in __get_indices
    self._get_metadata()
  File "/usr/local/lib/python2.7/dist-packages/curator/indexlist.py", line 158, in _get_metadata
    if not 'creation_date' in wl['settings']['index']:
KeyError: 'settings'
```

**Comment by untergeek** [comment] 2017-02-09 16:03
@volcomism I'm sorry it still doesn't work.  It does seem that while AWS ES does now support the `/_cluster/state` endpoint, it still does not contain the necessary information for Curator to populate its internal metadata store.  It seems that they should have tested that more carefully, as I know there are tickets open with regards to supporting Curator.

**Comment by streylight** [comment] 2017-02-22 20:51
The issue is that while `/_cluster/state` is exposed in Amazon ES 5 the`/_cluster/state/metadata` call returns everything but Settings for indices.  This fails because Curator tries to pull the index settings from the metadata [here](https://github.com/elastic/curator/blob/87e652711cd580cec9fadedaaf2d38f5f163e169/curator/indexlist.py#L149), which is why you're getting "KeyError: 'settings'" error. 

AWS is aware of the issue so hopefully it'll be supported soon.

**Comment by untergeek** [comment] 2017-02-22 21:03
@streylight do you have a link to an AWS ticket/issue/forum page?

**Comment by streylight** [comment] 2017-02-23 16:16
@untergeek I'm not aware of any public facing tickets but I work for AWS so I can assure you we're aware of it. If you'd like you can post on the forum and I can reply there for tracking purposes.

**Comment by barakalon** [comment] 2017-02-23 20:17
Added a ticket for this: https://forums.aws.amazon.com/thread.jspa?threadID=249967&tstart=0

**Comment by streylight** [comment] 2017-02-23 20:58
@barakalon Looks like the thread got locked.  Delete and resubmit it and I'll follow up with you there.

**Comment by barakalon** [comment] 2017-02-23 21:04
@streylight doesn't look like deleting it is an option 🤔 
I'm not sure why it got locked either.

**Comment by streylight** [comment] 2017-02-23 21:08
@barakalon I removed it.  Feel free to recreate it.

**Comment by streylight** [comment] 2017-02-23 21:21
Hey @barakalon direct message me (Jeremiah-AWS) on the forum and I'll help you. I don't want to clutter up this issue with AWS problems :)

**Comment by gregsterin** [comment] 2017-02-28 01:26
I just ran into this issue as well, and the AWS /_cluster/state/metadata endpoint still has this issue. 

This may be naive, but I was able to patch it by getting the data it seems to expect from the 'settings' from /index/_settings. Not sure if this introduces any unintended side effects, as this is my first time looking into this code base, but if it looks OK I'm happy to submit a PR for it.

It works for my use case of deleting old indices on AWS ES 5.

https://github.com/gregsterin/curator/commit/800fe19ce9792f5440688f0d41d99d18f78b7516

**Comment by untergeek** [comment] 2017-02-28 02:36
There are some missing pieces in _settings, so it works for only a limited number of use cases.

**Comment by untergeek** [comment] 2017-02-28 02:38
That was attempted in another PR, and it won't pass the unit and integration tests, so it was rejected as a workaround. I understand that AWS is aware of the issue and is working on a fix.

**Comment by jimmycuadra** [comment] 2017-03-30 21:03
@streylight Do you have any updates from AWS about this? AWS ES is not really useable for production for us without this, unfortunately. Is there another issue I should follow to track progress? Or a thread external to GitHub? Thanks much!

**Comment by ryananguiano** [comment] 2017-05-16 21:54
Even though this isn't merged due to tests, I got it to work for me with the following Dockerfile:

```
FROM python:2.7-slim

ADD https://github.com/Talend/curator/archive/638e4789ae02045d8a9153ba920b918fad2d01b5.tar.gz /curator.tgz

RUN tar zxf /curator.tgz && mv /curator-* /curator && pip install /curator/ && rm -rf /curator*
```

**Comment by nfelsen** [comment] 2017-06-01 22:09
AWS ES 5.3 was released today and it's fixing the support for Curator
https://aws.amazon.com/about-aws/whats-new/2017/06/elasticsearch-5-3-now-available-on-amazon-elasticsearch-service/

**Comment by untergeek** [comment] 2017-06-01 22:29
Please let me know how it goes.  I will have to change the support matrix and document how to use IAM credentials once it is confirmed.

**Comment by shavo007** [comment] 2017-06-01 23:39
awesome! let me know @nfelsen  how you go.

my team uses aws 5.1 and we will look to upgrade and test out curator in the future.

**Comment by jitran** [comment] 2017-06-02 09:59
i can confirm that curator works with aws elasticsearch 5.3

```
curator_cli --host mydomain --port 80 show_indices --verbose
.kibana              open   28.0KB      4   1   1 2017-06-02T00:26:34Z
logstash-2017.04.27  open  237.0KB    180   5   1 2017-06-02T00:48:46Z
logstash-2017.06.01  open    1.1MB   1740   5   1 2017-06-02T00:48:46Z
logstash-2017.06.02  open    9.2MB  30906   5   1 2017-06-02T00:48:45Z

curator_cli --host mydomain --port 80 delete_indices --filter_list '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":0},{"filtertype":"pattern","kind":"prefix","value":"logstash-"}]'
2017-06-02 11:05:43,894 INFO      Deleting selected indices: [u'logstash-2017.04.27', u'logstash-2017.06.01', u'logstash-2017.06.02']
2017-06-02 11:05:43,894 INFO      ---deleting index logstash-2017.04.27
2017-06-02 11:05:43,894 INFO      ---deleting index logstash-2017.06.01
2017-06-02 11:05:43,894 INFO      ---deleting index logstash-2017.06.02
2017-06-02 11:05:45,407 INFO      Singleton "delete_indices" action completed.
```

**Comment by shavo007** [comment] 2017-06-02 10:04
Awesome news  @jitran

**Comment by untergeek** [comment] 2017-06-02 14:31
@jitran is that with IAM credentials in your `curator.yml` file, then?

**Comment by jitran** [comment] 2017-06-03 22:35
@untergeek, IAM credentials in my curator.yml file didn't work with curator 5.0.4
```
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: TransportError(403, u'{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet on resource: mydomain"}')
```

I modified my elasticsearch access policy to allow my instance's ip address access and from there I was able to get curator to connect.

**Comment by jimmycuadra** [comment] 2017-06-08 01:51
Is curator supposed to automatically get credentials using the server's IAM instance role? Or does it need to be given an access key ID and secret via the configuration file? I'm guessing the latter because we're getting this in our logs from curator running on a server that has access to Elasticsearch Service via its IAM instance role:

```
2017-06-08 01:32:44,271 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/curator/cli.py", line 167, in cli
    client = get_client(**client_args)
  File "/usr/local/lib/python2.7/site-packages/curator/utils.py", line 784, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError((<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2bbcaf5290>, u'Connection to redacted.us-east-1.es.amazonaws.com timed out. (connect timeout=30)')) caused by: ConnectTimeoutError((<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2bbcaf5290>, u'Connection to redacted.us-east-1.es.amazonaws.com timed out. (connect timeout=30)'))
```

This is using curator version 5.0.4.

**Comment by untergeek** [comment] 2017-06-08 02:07
@jimmycuadra it does require the IAM credentials to be added to the configuration file.  It cannot pull the credentials from Elasticsearch.

**Comment by untergeek** [comment] 2017-06-08 02:08
@jimmycuadra @jitran I have no instance of AWS ES to play with, so I will be more than happy to merge any pull requests with fixes to the current setup.  I otherwise have no way to develop and test this. 😢

**Comment by cjuroz** [comment] 2017-06-08 02:27
I'll just like to add this python script I adapted from @jarpy. It uses curator api and aws4auth to sign requests to AWS ES and can be run as a Lambda function with appropriate iam role.

Most important: it works! It's aws es, curator and serverless :)

Here the code: https://gist.github.com/cjuroz/d45f4d73e74f068892c5e4f3d1c7fa7c

**Comment by jimmycuadra** [comment] 2017-06-08 22:11
> it does require the IAM credentials to be added to the configuration file. It cannot pull the credentials from Elasticsearch.

I'm a little confused by this. I'm not trying to pull credentials from Elasticsearch itself. I was asking about using an IAM role from an instance profile: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html. Generally programs that integrate with the AWS API support this automated system.

I found this in the changelog for curator v4:

> Experimental! Use AWS IAM credentials to sign requests to Elasticsearch. This requires the end user to manually install the requests_aws4auth python module.

That implies that it _does_ support what I was asking about. I'll try adding the `requests_aws4auth` Python package to my deployment of Curator and see if that makes it work. I quickly glanced at the code and didn't see where this module is being used to provide this behavior. I'll dig in further if just installing the package doesn't work.

**Comment by jimmycuadra** [comment] 2017-06-08 22:27
I found where the integration with `requests_aws4auth` happens: https://github.com/elastic/curator/blob/02a5028f18127fc351c9d7190befbb94ce21a4cb/curator/utils.py#L737

It actually does not attempt to get credentials using an instance profile, which seems to be a limitation of `requests_aws4auth` itself. I'll just generate credentials manually.

**Comment by cjuroz** [comment] 2017-06-09 02:55
@jimmycuadra it's not a limitation of `requests_aws4auth` as you can see in my previous comment here: 

https://gist.github.com/cjuroz/d45f4d73e74f068892c5e4f3d1c7fa7c#file-serverless-curator-py-L32 

A PR could be created to try open connection using IAM credentials. I think it should:

1. read configurations, if missing
2. read IAM credentials, try open ES connection with IAM credentials
3. if IAM credentials missing then use default ES connection kwargs

**Comment by jimmycuadra** [comment] 2017-06-09 06:18
@cjuroz The code in the gist you linked is not using the type of instance profile authentication I am talking about. It's pulling the credentials out of environment variables. Instance profile authentication works by making HTTP requests to the internal EC2 metadata service to get credentials.

**Comment by ralph-tice** [comment] 2017-07-14 05:08
@jimmycuadra you can whitelist your NAT gateway if your kubernetes nodes are in private subnet
but the right fix is to use the same sort of credentialsProviderChain that boto implements, example: https://github.com/sam-washington/requests-aws4auth/issues/14#issuecomment-231197951

I think #914 is the issue you are looking for in the Curator project.

**Comment by untergeek** [comment] 2018-03-20 16:06
With the change from #1172, I'm going to close this.  Amazon has improved the API call availability, and Curator seems to work just fine with everything 5.1 and up now.

**Closed by untergeek** 2018-03-20 16:06 UTC
Labels: KNOWN ISSUE
