### ISSUE TITLE
Curator not working on other RPM based distributions 

### ISSUE THREAD

**Issue by themoses** [elastic/curator#1159] opened 2018-03-05 09:25 UTC
### Expected Behavior
I installed the RPM Packages for CentOS 7 on a SLES 12 SP2 system using zypper/rpm since I have no option to use pip-install.

### Actual Behavior
Using curator --help results in a failure to call libssl.so.10 since it references to the /home/buh/ path to resolve it.

```
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run_curator.py", line 23, in <module>
  File "/home/buh/curator/curator/__init__.py", line 6, in <module>
  File "/home/buh/curator/curator/utils.py", line 2, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/__init__.py", line 17, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 2, in <module>
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
ImportError: libssl.so.10: cannot open shared object file: No such file or directory
```

Using the Packages for CentOS 6 like it has been done in #1127 shows no difference in behaviour.

### Specifications

  - Version: 5.4.1
  - Platform: SUSE Linux Enterprise Server 12 SP2
  - Kernel: 4.4.114-92.64-default

**Comment by untergeek** [comment] 2018-03-05 15:04
This would be a duplicate of #1124 

You need the OpenSSL 1.0.2 package for Curator to work.  I apologize for the inconvenience.

**Closed by untergeek** 2018-03-05 15:04 UTC

**Comment by xargs** [comment] 2018-07-25 16:33
Is this also applicable for SUSE 11 SP4 ? I am getting the same error.

**Comment by untergeek** [comment] 2018-07-25 23:59
No guarantees for SuSE-based distros.  The RPMs I make are tested on CentOS 6 and 7.
