### ISSUE TITLE
New action to handle updating dynamic index settings

### ISSUE THREAD

**Issue by shavo007** [elastic/curator#977] opened 2017-05-29 02:13 UTC
Hi,

I would like an action in curator to handle dynamic index settings.

After bulk indexing, I want to update the refresh interval back to 1s and potentially number of replicas.

My index template has refresh interval defined as -1. After successful index completion, i would like to use curator to update the index settings.

See:
https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#_disable_refresh_and_replicas_for_initial_loads

Curator 5.0.4

Thanks,
Shane.

**Comment by untergeek** [comment] 2017-05-29 02:55
Duplicate of #656

**Closed by untergeek** 2017-05-29 02:55 UTC

**Comment by shavo007** [comment] 2017-05-29 03:06
thanks for the update @untergeek  i assumed the other issue was just for replicas.
