### ISSUE TITLE
Curator 4.x not compatible with AWS ES with ES 2.3 due to AWS ES limitations

### ISSUE THREAD

**Issue by nathan-v** [elastic/curator#723] opened 2016-08-03 03:16 UTC
```
import elasticsearch
import curator
client = elasticsearch.Elasticsearch('https://somecoolcluster')
ilo = curator.IndexList(client)
print("Indices: {}".format(ilo.indices))
```

```
$ pip list
click (6.6)
elasticsearch (2.3.0)
elasticsearch-curator (4.0.4)
pip (8.1.2)
PyYAML (3.11)
setuptools (20.10.1)
urllib3 (1.16)
```

```
GET /_cluster/state/metadata/someindex [status:401 request:0.004s]
Traceback (most recent call last):
  File "./es_curation.py", line 43, in <module>
    ilo = curator.IndexList(client)
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/curator/indexlist.py", line 30, in __init__
    self.__get_indices()
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/curator/indexlist.py", line 70, in __get_indices
    self._get_metadata()
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/curator/indexlist.py", line 147, in _get_metadata
    index=to_csv(l),metric='metadata'
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/elasticsearch/client/cluster.py", line 75, in state
    'state', metric, index), params=params)
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, '{"Message":"Your request: \'/_cluster/state/metadata/someindex\' is not allowed."}')
```

AWS ES cluster with ES version 2.3. It appears getting a list of the indexes includes calls to /_cluster/state/ which isn't allowed by AWS ([reference](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg-supported-operations.html)).

It seems that the metadata call currently isn't wrapped up in a way that would allow it to fail gracefully ([reference](https://github.com/elastic/curator/blob/master/curator/indexlist.py#L70)).

Is it reasonable to return the index list with less data in the cases where we get back TransportError with status 401 for the metadata call? As it is now Curator is not compatible with AWS Elasticsearch Service with ES 2.3.

**Comment by untergeek** [comment] 2016-08-03 05:06
Duplicate of #717.

**Closed** 2016-08-03 05:09 UTC
