### ISSUE TITLE
Alias action fails entire action list when empty list returned, despite warn_if_no_indices and ignore_empty_list settings

### ISSUE THREAD

**Issue by bar0n36** [elastic/curator#1429] opened 2019-07-12 00:59 UTC
# Summary
When passing an action list to Curator containing 'Alias' actions, in the event an Alias action filter returns an empty list of indices, the entire action list is failed, rather than just that Alias action. The documentation for both ignore_empty_list and warn_if_no_indices reads that that action should fail, not the entire action list.
Even with ignore_empty_list and warn_if_no_indices set to True, the action and the entire action list fails with the error (incorrect):
Failed to complete action: alias.  <class 'curator.exceptions.ActionError'>: No "add" or "remove" operations

**warn_if_no_indices** description:
This setting specifies whether or not the alias action should continue with a warning or return immediately in the event that the filters in the add or remove section result in an empty index list.

**ignore_empty_list** description:
When the ignore_empty_list option is set to True, the action will exit with an INFO level log message indicating such. If ignore_empty_list is set to False, an ERROR level message will be logged, and Curator will exit with code 1.

# Expected Behavior
With either of these values set to True, the Action should exit with a Warning, and the action list should continue on to the next item.

# Actual Behavior
As soon as an Alias action with an empty list is encountered, the entire action list fails with an 'Failed to complete action: alias.  <class 'curator.exceptions.ActionError'>: No "add" or "remove" operations' error

# Steps to Reproduce the Problem
Contents of file 'Action-Alias.yml'
```
# Remove logs-active alias from indices older than X days
  1:
    action: alias
    description: >-
      Remove active alias from logs indices
    options:
      name: logs-active
      ignore_empty_list: True
      disable_action: False
      warn_if_no_indices: (true or false)
    remove:
      filters:
      - filtertype: pattern
        kind: prefix
        value: logs-20
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 5

# Remove metrics-active alias from indices older than X days
  2:
    action: alias
    description: >-
      Remove active alias from metrics indices
    options:
      name: metrics-active
      ignore_empty_list: True
      disable_action: False
      warn_if_no_indices: (true or false)
    remove:
      filters:
      - filtertype: pattern
        kind: prefix
        value: metrics-20
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 5
```
Execute the action file via command such as:
/usr/bin/curator --config hostConnection.yml Action-Alias.yml

Output:
2019-07-12 10:42:02,710 INFO      Preparing Action ID: 1, "alias"
2019-07-12 10:42:02,849 INFO      Trying Action ID: 1, "alias": Remove active alias from logs indices
2019-07-12 10:42:04,849 INFO      Updating aliases...
2019-07-12 10:42:04,849 ERROR     Failed to complete action: alias.  <class 'curator.exceptions.ActionError'>: No "add" or "remove" operations

# Specifications
  - Version: 5.6
  - Platform: RHEL 6

# Impact of Issue
Due to this issue I have had to introduce the catch all option 'continue_if_exception: True' to my Action file to allow it to continue. This is not desirable as I would rather if there was a significant failure the curator job failed completely.

# Proposal:
Ensure that both ignore_empty_list and warn_if_no_indices options are honoured by Curator.

**Comment by untergeek** [comment] 2019-07-12 15:38
You are attempting to execute the `alias` action with no `add` or `remove` statements. This is an invalid behavior, which raises an error condition. You are asking for me to have `ignore_empty_list` catch this? That is a worrisome thing to me, because instead of catching an error—which it is—you are asking me to replace it with something else. I'm not sure how I feel about it. Code-wise, it's not a problem to have it raise an empty list condition and let that be handled like it normally is. It will break all kinds of tests I have in place already. I will have to change a lot of things for this. Replacing a legitimate error with this doesn't feel quite right to me. On the other hand, it makes sense in cases like yours, where the lack of `add` and `remove` is because there are no indices. I can probably code around it to raise empty list if the lack of add/remove is due to empty list, but I still hesitate.

Thoughts? Ideas?

**Comment by bar0n36** [comment] 2019-07-15 03:59
I'm not sure what you mean by suggesting no add/remove statements? There are remove statements in both code blocks I posted as examples? Below it is again but properly highlighted as a code block this time. (sorry, missed highlighting that properly in the original issue)

Contents of file 'Action-Alias.yml'
```
# Remove logs-active alias from indices older than X days
1:
  action: alias
  description: >-
    Remove active alias from logs indices
  options:
    name: logs-active
    ignore_empty_list: True
    disable_action: False
    warn_if_no_indices: (true or false)
  remove:
    filters:
    - filtertype: pattern
      kind: prefix
      value: logs-20
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 5

# Remove metrics-active alias from indices older than X days
2:
  action: alias
  description: >-
    Remove active alias from metrics indices
  options:
    name: metrics-active
    ignore_empty_list: True
    disable_action: False
    warn_if_no_indices: (true or false)
  remove:
    filters:
    - filtertype: pattern
      kind: prefix
      value: metrics-20
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 5
```

I would not request you to replace a valid exception with another, but to me, there are action elements defined (remove), so surely the exception around no add or remove statements is invalid, and an empty list exception would be more appropriate?

I haven't reviewed the source of curator, so potentially I am misunderstanding how it processes the action YAML, so my apologies if I am missing the point.

**Comment by untergeek** [comment] 2019-07-15 06:53
Sorry for the confusion. When I said, "no add or remove statements," I mean add or remove array elements. For each index remaining in the list after processing all filters, an array element is appended to the add or remove list, respectively. When it's time to perform the action, Curator builds the API call from these arrays. If there is nothing in the add array, and nothing in the remove array, you get the condition I was describing (badly), where you are attempting to perform an API call, but there is effectively nothing to add or remove. This is the error condition I was trying to describe. I presumed familiarity with the code, which is my bad.

**Comment by bar0n36** [comment] 2019-07-16 03:56
OK. That makes sense and I assumed that it must work something like that based on your comments, but I haven't had a chance to look into it.

Surely that should be handled by either the warn_if_no_indices (the description of this setting matches this scenario exactly in my interpretation) or ignore_empty_list flags?

**Comment by untergeek** [comment] 2019-07-16 04:12
I have explained my position already:

> I can probably code around it to raise empty list if the lack of add/remove is due to empty list

I will see about adding code to check if there are no elements in the add or remove array and raising the "empty list" condition, and log an error. At that point, it should function the way you envision with `ignore_empty_list`.

**Comment by bar0n36** [comment] 2019-07-16 04:29
OK. Can you clarify the description of the warn_if_no_indices setting in the documentation? The way I interpret the description for that option reads exactly as to what I am trying to do. 

If my interpretation is incorrect, can you re-align me, or reword the documentation to make it less ambiguous to avoid this coming up again in the future? This documentation does not appear to have been revised for 5.7.

![Curator_warn_if_no_indices](https://user-images.githubusercontent.com/30456919/61265921-e39b7700-a7d5-11e9-84fe-63870f98345f.PNG)

**Comment by untergeek** [comment] 2019-07-16 05:20
Documentation will be updated to reflect that `ignore_empty_list` will catch when both `add` and `remove` are empty, and `warn_if_no_indices` will warn when one of either `add` or `remove` are empty, but not both.

**Comment by untergeek** [comment] 2019-07-18 03:53
## Unable to reproduce problem

I actually cannot replicate what you're seeing. The code should already do what you expect, and what the documentation says it does.

## Description of code for alias add/remove 

Two separate IndexList objects (`ilo`) are used for the add and remove code blocks. As they are functionally identical, I will show [just the one for `add`](https://github.com/elastic/curator/blob/v5.7.6/curator/actions.py#L51-L64):

```
        try:
            ilo.empty_list_check()
        except exceptions.NoIndices:
            # Add a warning if there are no indices to add, if so set in options
            if warn_if_no_indices:
                self.warn_if_no_indices = True
                self.loggit.warn(
                    'No indices found after processing filters. '
                    'Nothing to add to {0}'.format(self.name)
                )
                return
            else:
                # Re-raise the exceptions.NoIndices so it will behave as before
                raise exceptions.NoIndices('No indices to add to alias')
```

If the filters provided have resulted in the IndexList object having no actionable indices, it will be caught by the `ilo.empty_list_check()` test. The `except` case catches a `NoIndices` exception and subsequently checks to see if `warn_if_no_indices` is `True` (which is passed to the add or remove method alongside the IndexList object). If it is, it sets the internal object `self.warn_if_no_indices` to `True` and logs a warning. If `warn_if_no_indices` is `False`, then it _immediately_ raises a `NoIndices` exception, which will halt further execution of the current action.

## Description of code for generating the API "body" 

When it comes time to actually perform the atomic add/remove actions, Curator generates the "body" of the API call with [these pre-tests](See https://github.com/elastic/curator/blob/v5.7.6/curator/actions.py#L123-L127 for direct link):

```
        if not self.actions:
            if not self.warn_if_no_indices:
                raise exceptions.ActionError('No "add" or "remove" operations')
            else:
                raise exceptions.NoIndices('No "adds" or "removes" found.  Taking no action')
```

If `self.actions` is empty (`self.actions` will have add and remove actions appended for each matching index, so if it's empty, that means there's nothing to add or remove), it tests the next condition, "is `self.warn_if_no_indices` `true` or `false`? If it is `false`, raise the `ActionError`. If it is `true`, raise the `NoIndices` error.

## Test config
```
---
actions:
  1:
    action: delete_indices
    options:
      ignore_empty_list: true
    filters:
      - filtertype: pattern
        kind: prefix
        value: foo
  2:
    action: create_index
    options:
      name: foo
  3:
    action: alias
    options:
      ignore_empty_list: true
      warn_if_no_indices: true
      name: foo_alias
    add:
      filters:
        - filtertype: pattern
          kind: prefix
          value: foo
  4:
    action: alias
    options:
      ignore_empty_list: true
      warn_if_no_indices: true
      name: foo_alias
    remove:
      filters:
        - filtertype: pattern
          kind: prefix
          value: bar
  5:
    action: delete_indices
    options:
      ignore_empty_list: true
    filters:
      - filtertype: pattern
        kind: prefix
        value: foo
```

## Flow description

* cleanup first, in case there was a problem before (action 1)
* create an index which will do nothing (action 2)
* create alias `foo_alias` with index `foo` (action 3) so there is an actual alias to test against, 
* *attempt to remove indices starting with `bar` from alias `foo_alias`* (action 4) — this is what you are reporting as not working
* cleanup index `foo` (action 5).

## Results

### `ignore_empty_list` is `true` and `warn_if_no_indices` is `true`

```
2019-07-18 13:19:07,794 INFO      Preparing Action ID: 1, "delete_indices"
2019-07-18 13:19:07,799 INFO      Trying Action ID: 1, "delete_indices": No description given
2019-07-18 13:19:07,801 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2019-07-18 13:19:07,801 INFO      Action ID: 1, "delete_indices" completed.
2019-07-18 13:19:07,801 INFO      Preparing Action ID: 2, "create_index"
2019-07-18 13:19:07,803 INFO      Trying Action ID: 2, "create_index": No description given
2019-07-18 13:19:07,803 INFO      Creating index "foo" with settings: {}
2019-07-18 13:19:08,013 INFO      Action ID: 2, "create_index" completed.
2019-07-18 13:19:08,013 INFO      Preparing Action ID: 3, "alias"
2019-07-18 13:19:08,015 INFO      Trying Action ID: 3, "alias": No description given
2019-07-18 13:19:08,028 INFO      Updating aliases...
2019-07-18 13:19:08,028 INFO      Alias actions: {'actions': [{'add': {'index': 'foo', 'alias': 'foo_alias'}}]}
2019-07-18 13:19:08,069 INFO      Action ID: 3, "alias" completed.
2019-07-18 13:19:08,069 INFO      Preparing Action ID: 4, "alias"
2019-07-18 13:19:08,071 INFO      Trying Action ID: 4, "alias": No description given
2019-07-18 13:19:08,084 WARNING   No indices found after processing filters. Nothing to remove from foo_alias
2019-07-18 13:19:08,084 INFO      Updating aliases...
2019-07-18 13:19:08,084 INFO      Skipping action "alias" due to empty list: <class 'curator.exceptions.NoIndices'>
2019-07-18 13:19:08,084 INFO      Action ID: 4, "alias" completed.
2019-07-18 13:19:08,084 INFO      Preparing Action ID: 5, "delete_indices"
2019-07-18 13:19:08,088 INFO      Trying Action ID: 5, "delete_indices": No description given
2019-07-18 13:19:08,099 INFO      Deleting 1 selected indices: ['foo']
2019-07-18 13:19:08,099 INFO      ---deleting index foo
2019-07-18 13:19:08,154 INFO      Action ID: 5, "delete_indices" completed.
2019-07-18 13:19:08,154 INFO      Job completed.
```

I see:
```
WARNING   No indices found after processing filters. Nothing to remove from foo_alias
```
followed by
```
Skipping action "alias" due to empty list: <class 'curator.exceptions.NoIndices'>
```
which indicates that `warn_if_no_indices: true` is producing the expected warning.

### ### `ignore_empty_list` is `true` and `warn_if_no_indices` is `false`

```
2019-07-18 13:24:00,451 INFO      Preparing Action ID: 1, "delete_indices"
2019-07-18 13:24:00,455 INFO      Trying Action ID: 1, "delete_indices": No description given
2019-07-18 13:24:00,458 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2019-07-18 13:24:00,458 INFO      Action ID: 1, "delete_indices" completed.
2019-07-18 13:24:00,458 INFO      Preparing Action ID: 2, "create_index"
2019-07-18 13:24:00,460 INFO      Trying Action ID: 2, "create_index": No description given
2019-07-18 13:24:00,460 INFO      Creating index "foo" with settings: {}
2019-07-18 13:24:00,675 INFO      Action ID: 2, "create_index" completed.
2019-07-18 13:24:00,675 INFO      Preparing Action ID: 3, "alias"
2019-07-18 13:24:00,678 INFO      Trying Action ID: 3, "alias": No description given
2019-07-18 13:24:00,691 INFO      Updating aliases...
2019-07-18 13:24:00,691 INFO      Alias actions: {'actions': [{'add': {'index': 'foo', 'alias': 'foo_alias'}}]}
2019-07-18 13:24:00,723 INFO      Action ID: 3, "alias" completed.
2019-07-18 13:24:00,723 INFO      Preparing Action ID: 4, "alias"
2019-07-18 13:24:00,726 INFO      Trying Action ID: 4, "alias": No description given
2019-07-18 13:24:00,741 INFO      Skipping action "alias" due to empty list: <class 'curator.exceptions.NoIndices'>
2019-07-18 13:24:00,741 INFO      Action ID: 4, "alias" completed.
2019-07-18 13:24:00,741 INFO      Preparing Action ID: 5, "delete_indices"
2019-07-18 13:24:00,743 INFO      Trying Action ID: 5, "delete_indices": No description given
2019-07-18 13:24:00,754 INFO      Deleting 1 selected indices: ['foo']
2019-07-18 13:24:00,755 INFO      ---deleting index foo
2019-07-18 13:24:00,797 INFO      Action ID: 5, "delete_indices" completed.
2019-07-18 13:24:00,797 INFO      Job completed.
```

I see:
```
Skipping action "alias" due to empty list: <class 'curator.exceptions.NoIndices'>
```
with no preceding `WARNING` about an empty list.

### Run with `ignore_empty_list: false`

In the previous test cases, the `ignore_empty_list: true` setting allowed the cleanup action, number 5, to proceed, which says to me that `ignore_empty_list: true` is doing exactly what one would expect.

In order to prove it would raise an error with it set to `false`, I ran one more time with `ignore_empty_list: false` and this is what I saw:

```
2019-07-18 13:29:20,799 INFO      Preparing Action ID: 1, "delete_indices"
2019-07-18 13:29:20,803 INFO      Trying Action ID: 1, "delete_indices": No description given
2019-07-18 13:29:20,806 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2019-07-18 13:29:20,806 INFO      Action ID: 1, "delete_indices" completed.
2019-07-18 13:29:20,806 INFO      Preparing Action ID: 2, "create_index"
2019-07-18 13:29:20,807 INFO      Trying Action ID: 2, "create_index": No description given
2019-07-18 13:29:20,808 INFO      Creating index "foo" with settings: {}
2019-07-18 13:29:20,992 INFO      Action ID: 2, "create_index" completed.
2019-07-18 13:29:20,992 INFO      Preparing Action ID: 3, "alias"
2019-07-18 13:29:20,994 INFO      Trying Action ID: 3, "alias": No description given
2019-07-18 13:29:21,006 INFO      Updating aliases...
2019-07-18 13:29:21,006 INFO      Alias actions: {'actions': [{'add': {'index': 'foo', 'alias': 'foo_alias'}}]}
2019-07-18 13:29:21,038 INFO      Action ID: 3, "alias" completed.
2019-07-18 13:29:21,038 INFO      Preparing Action ID: 4, "alias"
2019-07-18 13:29:21,041 INFO      Trying Action ID: 4, "alias": No description given
2019-07-18 13:29:21,055 ERROR     Unable to complete action "alias".  No actionable items in list: <class 'curator.exceptions.NoIndices'>
$ echo $?
1
```

I see that it did not attempt action 5 because action 4 resulted in an `ERROR`. The exit code was `1`, because it did not terminate cleanly.

## Conclusion

I cannot replicate what you are describing. I do not understand why you are seeing what you are seeing, as I have worked hard to replicate the conditions. I even added the exact `age` filter you had in place, hoping that adding the filter as you had it would trigger the same conditions you encountered. I do not know what to say.

**Comment by bar0n36** [comment] 2019-07-18 23:40
Fair enough. I will upgrade Curator to 5.7 and see how I go. I did check the release notes for 5.7 before I raised this issue and found nothing that would have suggested a fix to this, hence why I raised the issue.
Thanks very much for looking into it.

**Comment by untergeek** [comment] 2019-08-02 03:28
Closing for now. Please feel free to re-open when/if you obtain any new information regarding this.

**Closed by untergeek** 2019-08-02 03:28 UTC
Labels: cannot_replicate
