### ISSUE TITLE
curator_cli 5 doesn't support show_indices and show_snapshots anymore ?

### ISSUE THREAD

**Issue by tobymaro** [elastic/curator#1281] opened 2018-10-05 07:09 UTC
## To submit a bug or report an issue

curator_cli show-indices doesn't work anymore . The same for show-snapshots.

### Expected Behavior
curator_cli show-indices - should return list of available indices 

### Actual Behavior
]# curator_cli show-indices
2018-10-05 07:03:41,289 CRITICAL  Action must be one of ['snapshot', 'create_index', 'index_settings', 'rollover', 'forcemerge', 'cluster_routing', 'replicas', 'delete_indices', 'allocation', 'alias', 'restore', 'close', 'delete_snapshots', 'open', 'shrink', 'reindex']
Traceback (most recent call last):
  File "/bin/curator_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/curator/curator_cli.py", line 8, in main
    cli(obj={})
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/show.py", line 21, in show_indices
    action = cli_action(ctx.info_name, ctx.obj['config']['client'], {'allow_ilm_indices': allow_ilm_indices}, filter_list, ignore_empty_list)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/object_class.py", line 52, in __init__
    self.check_options(option_dict)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/object_class.py", line 103, in check_options
    options.get_schema(self.action),
  File "/usr/lib/python2.7/site-packages/curator/validators/options.py", line 144, in get_schema
    for each in action_specific(action):
  File "/usr/lib/python2.7/site-packages/curator/validators/options.py", line 129, in action_specific
    return options[action]
KeyError: u'show-indices'

### Steps to Reproduce the Problem
curator_cli show-indices 

### Specifications

  - Version: curator_cli 5.5.4
  - Platform: Centos 7
  - Subsystem: systemd
  - Python: 2.7
  - Elasticsearch 6.4

**Comment by untergeek** [comment] 2018-10-05 10:12
This is a duplicate of #1279

**Closed by untergeek** 2018-10-05 10:12 UTC
