### ISSUE TITLE
Better document how to use SSL certificates

### ISSUE THREAD

**Issue by sagh0900** [elastic/curator#729] opened 2016-08-10 16:03 UTC
curator --version
curator, version 4.0.5

**config file:**
client:
  hosts:
    - localhost
  port: 9200
  url_prefix:
  use_ssl: True
  certificate: /usr/local/bin/root-ca.pem
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth: admin:pass
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:  curator.log
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

**Action_File:**
actions:
  1:
    action: open
    description: >-
      Open indices older than 1 days but younger than 2 days (based on index
      name), for default- prefixed indices.
    options:
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: default-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 2
      exclude:
    - filtertype: age
      source: name
      direction: younger
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
      exclude:

[root@elk-master ~]$ curator "action_file.yml"
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html

**curator.log**, which is created:

2016-08-10 15:48:35,700 INFO      Action #1: open
2016-08-10 15:48:35,729 ERROR     Unable to complete action "open".  No actionable items in list: <class 'curator.exceptions.NoIndices'>
2016-08-10 15:49:46,108 INFO      Action #1: open
2016-08-10 15:49:46,138 ERROR     Unable to complete action "open".  No actionable items in list: <class 'curator.exceptions.NoIndices'>
2016-08-10 15:54:26,930 INFO      Action #1: open
2016-08-10 15:54:26,959 ERROR     Unable to complete action "open".  No actionable items in list: <class 'curator.exceptions.NoIndices'>

This is totally cubersome, where to add certificate for verification and which certificate? I tried all my possible ways, but no luck. I have root-ca.pem which is kind of signed certificate which I used in kibana.yml and working perfectly. Please someone help me.

As an ending note: I'm new to CURATOR and as well using it in secured environment.

**Comment by untergeek** [comment] 2016-08-10 16:14
How is Elasticsearch secured?  Is it using the Shield plugin?  Or is it behind an SSL proxy or something like that?

**Comment by sagh0900** [comment] 2016-08-11 08:52
no its not behind in any proxy. I'm using search-guard. But that is irrelavent for curator, right?

**Comment by untergeek** [comment] 2016-08-11 15:24
I don't know if it's relevant, but Curator has been tested with Shield and is known to work with that.

**Comment by untergeek** [comment] 2016-08-11 15:31
Also, running with `loglevel: DEBUG` and attaching the resulting file will help with debugging.

**Comment by untergeek** [comment] 2016-08-11 15:33
And you may try setting `ssl_no_validate: True`, as that is what helped with [this older ticket](https://discuss.elastic.co/t/curator-over-ssl/52303).

**Comment by sagh0900** [comment] 2016-08-12 10:04
Thanks for your replies. I downgraded by curator version to 3.5.1. The following commands before elasticsearch secured was working perfectly, of course security flags weren't included.

> curator --loglevel DEBUG --use_ssl --ssl-no-validate --host 192.168.0.1 --http_auth admin:admin --certificate "/usr/local/bin/root-ca.pem" --port 9200 show indices --all-indices
> 2016-08-12 09:48:57,597 INFO      Job starting: show indices

**output:**

> 2016-08-12 09:48:57,597 DEBUG     Params: {'url_prefix': u'', 'http_auth': uadmin:admin', 'dry_run': False, 'certificate': u'/usr/local/bin/root-ca.pem', 'loglevel': u'DEBUG', 'logformat': u'default', 'client_cert': None, 'host': u'192.168.0.1', 'quiet': False, 'timeout': 30, 'debug': False, 'use_ssl': True, 'logfile': None, 'master_only': False, 'port': 9200, 'ssl_no_validate': True, 'client_key': None}
> 2016-08-12 09:48:57,597 DEBUG     kwargs = {'url_prefix': u'', 'http_auth': u'admin:admin', 'dry_run': False, 'certificate': u'/usr/local/bin/root-ca.pem', 'loglevel': u'DEBUG', 'host': u'192.168.0.1', 'quiet': False, 'port': 9200, 'logformat': u'default', 'timeout': 30, 'debug': False, 'use_ssl': True, 'logfile': None, 'master_only': False, 'client_cert': None, 'ssl_no_validate': True, 'client_key': None}
> /usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:70: UserWarning: Connecting to 192.168.0.1 using SSL with verify_certs=False is insecure.
>   'Connecting to %s using SSL with verify_certs=False is insecure.' % host)


If I include --master-only flag in the above working command, then again its says the following: (But I'm running this command on elected master host)

> curator --master-only --loglevel DEBUG --use_ssl --host 172.16.189.41 --http_auth elk-master:VGTCloudInfra --certificate "/usr/local/bin/root-ca.pem" --port 9200 show indices --all-indices

> 2016-08-12 09:58:11,322 INFO      Job starting: show indices
> 2016-08-12 09:58:11,322 DEBUG     Params: {'url_prefix': u'', 'http_auth': u'admin:admin', 'dry_run': False, 'certificate': u'/usr/local/bin/root-ca.pem', 'loglevel': u'DEBUG', 'logformat': u'default', 'client_cert': None, 'host': u'192.168.0.1', 'quiet': False, 'timeout': 30, 'debug': False, 'use_ssl': True, 'logfile': None, **'master_only': True,** 'port': 9200, 'ssl_no_validate': False, 'client_key': None}
> 2016-08-12 09:58:11,322 DEBUG     kwargs = {'url_prefix': u'', 'http_auth': u'admin:admin', 'dry_run': False, 'certificate': u'/usr/local/bin/root-ca.pem', 'loglevel': u'DEBUG', 'host': u'192.168.0.1', 'quiet': False, 'port': 9200, 'logformat': u'default', 'timeout': 30, 'debug': False, 'use_ssl': True, 'logfile': None, 'master_only': True, 'client_cert': None, 'ssl_no_validate': False, 'client_key': None}
> 2016-08-12 09:58:11,323 INFO      Attempting to verify SSL certificate.
> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
>   InsecureRequestWarning)
> 2016-08-12 09:58:11,336 DEBUG     Detected Elasticsearch version 2.3.4
> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
>   InsecureRequestWarning)
> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
>   InsecureRequestWarning)
> 2016-08-12 09:58:11,341 INFO      **Master-only flag detected. Connected to non-master node. Aborting.**


**The following is not working, but still how to avoid "certificate add" exceptions?**

>  curator --loglevel DEBUG --use_ssl --ssl-no-validate --host 192.168.0.1 --http_auth admin:admin --certificate "/usr/local/bin/root-ca.pem" --port 9200 show indices --all-indices

Job starting: show indices
2016-08-12 09:54:00,476 DEBUG     Params: {'url_prefix': u'', 'http_auth': u'admin:admin', 'dry_run': False, 'certificate': u'/usr/local/bin/root-ca.pem', 'loglevel': u'DEBUG', 'logformat': u'default', 'client_cert': None, 'host': u'192.168.0.1', 'quiet': False, 'timeout': 30, 'debug': False, 'use_ssl': True, 'logfile': None, 'master_only': False, 'port': 9200, 'ssl_no_validate': True, 'client_key': None}
2016-08-12 09:54:00,476 DEBUG     kwargs = {'url_prefix': u'', 'http_auth': u'admin:admin', 'dry_run': False, 'certificate': u'/usr/local/bin/root-ca.pem', 'loglevel': u'DEBUG', 'host': u'192.168.0.1', 'quiet': False, 'port': 9200, 'logformat': u'default', 'timeout': 30, 'debug': False, 'use_ssl': True, 'logfile': None, 'master_only': False, 'client_cert': None, 'ssl_no_validate': True, 'client_key': None}
/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:70: UserWarning: Connecting to 192.168.0.1 using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
2016-08-12 09:54:00,485 ERROR     Connection failure.

**Comment by untergeek** [comment] 2016-08-12 16:43
I do not recommend downgrading to 3.5.1.  The linked example was simply using 3.5.1.  The message, as you have seen, is the same.

```
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)
```
This is a non-fatal warning.  You likely cannot get rid of it if you are using self-signed certificates, or there are missing intermediate certificates, or any other number of possible permutations.  It simply says, "I'm not verifying the certificate, just so you know," and then it continues on its merry way.  I have no way of knowing how your certificates were generated, or by whom they were signed.  Curator itself only delegates that testing to the `urllib3` python module, and that module says there's something wrong in the certificate chain.  It's that simple.  Perhaps `urllib3` is pickier than Kibana.  I don't know.  Kibana may still be generating errors in the log file related to the certificate chain, but it keeps working anyway.  I don't have that information handy as it's in your environment.

Using `--master-only` is probably not needed in your use case.  It is used when deploying Curator to _all_ nodes in the cluster, but only having it _complete_ the run on the elected master.

**Comment by untergeek** [comment] 2016-08-15 22:05
Any update, @sagh0900 ?

**Comment by sagh0900** [comment] 2016-08-18 11:00
@untergeek Sorry I was down with flu for past three days. I got your point. But isn't there way to get rid of them by either working around or adding certs as it is saying? We are using self-signed certificates.

Regarding --master-only flag: Yes we have curator deployed in all nodes in the cluster. And I even tried to run curator with --master-only in elected master node, still it throws "non-master node detected" error.

**Comment by inqueue** [comment] 2016-09-01 15:31
```
curator --version && python -V
curator, version 4.0.6
Python 3.4.3
```

@untergeek Using Curator against Elastic Cloud will reproduce the behavior. 

```
cat config.yml
client:
  hosts:
    - 9a6ed25bbc72800abad46167e3fb5152.us-east-1.aws.found.io:9243
  use_ssl: True
  ssl_no_validate: False
  http_auth: some_user:anyonesguess
```

```
/usr/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py:70: UserWarning: Connecting to 9a6ed25bbc72800abad46167e3fb5152.us-east-1.aws.found.io using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
/usr/lib/python3.4/site-packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
```

From my research, it looks like `urllib3` needs a reference to the OS CA bundle since, by default, it does not do any certificate verification. This configuration on CentOS7 allows Curator to work with EC's public cert without warnings:

```
certificate: /etc/ssl/certs/ca-bundle.crt
```

Alternatively, if I only want EC's trust in my Curator config, then I can place its CA root and intermediate in a bundle and configure the `certificate` setting:

```
  ssl_no_validate: False
  certificate: /opt/es-curator/es-cloud-ca-bundle.pem
```

This will again ignore the OS bundle since, by default, it is not referenced by `urllib3` and uses the `certificate` configuration for verification. I have not tested it yet, but the same should be true for self-signed certificates since `urllib3` makes no distinction.

Hopefully we can at least better document how to make this work.

**Comment by untergeek** [comment] 2016-09-01 16:48
@sagh0900  Have you tried installing the `certifi` module?  It is supposed to provide those CAs.  Yes, the OS-provided one _can_ work, but the `certifi` python module is also supposed to provide those.  If `certificate` is not specified, and the `certifi` module is installed, Curator should use that.

This behavior is in [these lines of code](https://github.com/elastic/curator/blob/9d4c819e225198452906bd2693fc8b67e321b8c2/curator/utils.py#L505-L520).

**Comment by untergeek** [comment] 2016-09-01 16:48
@inqueue Thanks for reporting your findings.  That helps.

**Comment by sagh0900** [comment] 2016-09-02 08:12
Aah.. I tried certifi as well. I really appreciate you both for trying to help me out. This info helps. If I do have anything else, I will update here or open new issue if it falls in different category. For now, I'm good.

**Comment by untergeek** [comment] 2017-03-27 23:28
With the upgrade to Curator 4.2, and providing self-contained versions for linux and windows, most of the issues with certificates seem to have been resolved.  This is chiefly because older versions of Python are not being used (with their SSL issues), and `certifi` is bundled.  I'm going to close this.

**Closed by untergeek** 2017-03-27 23:28 UTC
Labels: Documentation
