### ISSUE TITLE
Link to download yum package broken

### ISSUE THREAD

**Issue by Ryanasaurus** [elastic/curator#1583] opened 2021-01-11 21:10 UTC
Cannot get the newest packages from the repository as the link doesn't work.
Installation guide provides this url for getting the most recent package, 5.8.3
https://packages.elastic.co/curator/5/centos/7/Packages/elasticsearch-curator-5.8.3-1.x86_64.rpm
But this link doesn't resolve, instead it gives a not found

### Expected Behavior
Give the expected package

### Actual Behavior
Shows error message says Not Found

## Context (Environment)
Trying to test an update from curator 5.8.1 to 5.8.3 as part of regular patching

**Comment by untergeek** [comment] 2021-01-11 21:12
Duplicate of #1573 and #1578

**Closed by untergeek** 2021-01-11 21:12 UTC
