### ISSUE TITLE
Filter element exclude should throw an error when not True, False, or Blank

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/curator#708] opened 2016-07-27 14:35 UTC
During testing of configuration of curator a mistake in using exclude as a file name pattern rather than a boolean value led to unexpected results.  The filter did not function at all and did not indicate an error in it's configuration at run time.

**Comment by untergeek** [comment] 2016-07-27 14:45
Duplicate of #674

**Closed by untergeek** 2016-07-27 14:45 UTC
