### ISSUE TITLE
Could not make curator 4.1.2 work with SSL/TLS and client certificates

### ISSUE THREAD

**Issue by floragunncom** [elastic/curator#780] opened 2016-10-09 12:18 UTC
I tried to make curator 4.1.2 work (on Ubuntu, ES 2.4.0) with the following configuration:

<pre>
client:
  hosts:
    - "host1"
    - "host2"
  port: 9200
  url_prefix:
  use_ssl: True
  certificate: '/path/to/chain-ca.pem'
  client_cert: '/path/to/client.pem'
  client_key: '/path/to/key.pem'
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False
</pre>

If installed curator with ``apt-get install python-elasticsearch-curator`` or ``apt-get install elasticsearch-curator`` i face this warnings:

<pre>
SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication)
extension to TLS is not available on this platform. This may cause the server to present an 
incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version 
of Python to solve this. For more information, see 
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

InsecurePlatformWarning: A true 
SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and 
may cause certain SSL connections to fail. You can upgrade to a newer version of Python to 
solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-
usage.html#ssl-warnings

And then it fails with:

File "/tmp/curator/curator-4.1.2/curator/cli.py", line 165, in cli
File "/tmp/curator/curator-4.1.2/curator/utils.py", line 587, in get_client
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to 
Elasticsearch.  Error: ConnectionError(error return without exception set) caused by: 
SystemError(error return without exception set)
</pre>

If installed curator with ``apt-get install python3-elasticsearch-curator`` curator gives this error:
<pre>
Traceback (most recent call last):
File "/usr/local/bin/curator", line 5, in <module>
from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
</pre>

Please note:
Other clients like browsers, curl, logstash and beats can connect to elasticsearch without any problems using the identical certificates and keys.

I can also successfully access elasticsearch from es python client (tested with python3):

<pre>
es = Elasticsearch(
    ['host1:9200'],
    connection_class=RequestsHttpConnection,
    use_ssl=True,
    verify_certs=True,
    ca_certs='/path/to/chain-ca.pem',
    client_cert='/path/to/client.pem',
    ssl_version=ssl.PROTOCOL_TLSv1_2,
    ssl_assert_hostname=True,
    client_key='/path/to/key.pem'
    )
print(es.info())
</pre>

I can also successfully access elasticsearch using urllib3 directly (tested with python3) but only if pyopenssl is enforced:

<pre>
#without forcing urllib3 to pyopenssl connection will fail
urllib3.contrib.pyopenssl.inject_into_urllib3()

http = urllib3.PoolManager(
ca_certs="/path/to/chain-ca.pem",
cert_reqs='CERT_REQUIRED',
cert_file='/path/to/client.pem',
key_file='//path/to/key.pem',
)

r = http.request('GET', 'https://host1:9200')
udata=r.data
print(udata)
</pre>

**Comment by untergeek** [comment] 2016-10-09 13:30
Thank you for this report.  I will be investigating tomorrow.  In the meanwhile, could you please provide some additional information?

* Which version of Linux are you using? 
* Which patch level?
* Which version(s) of Python are you using to test? Both 2 and 3.
* How are the certificates signed? By which provider?

Knowing which version of Linux and Python are shipping without the `SNI (Subject Name Indication)
extension to TLS` will help me a great deal.  Truthfully, I'm surprised that this error would crop up with the binary package, as it was built with Python 2.7.12 on Ubuntu 16.04, but I will do what I can to verify this.

Also, with regards to this error:

>```
Traceback (most recent call last):
File "/usr/local/bin/curator", line 5, in 
from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

Please install `setuptools`, per [this FAQ entry](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/entrypoint-fix.html) in the documentation.  Up to date versions are provided in the Curator apt repository, e.g. `python3-setuptools`.  That will allow you to test this with Python3.

**Comment by floragunncom** [comment] 2016-10-09 18:52
<pre>
$ apt-get install -y python3-pip python3-elasticsearch-curator=4.1.2
$ pip3 install -U setuptools
Successfully installed setuptools-28.3.0
</pre>
results in
<pre>
File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 856, 
in resolve raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'elasticsearch-curator==4.1.2' distribution 
was not found and is required by the application
</pre>

pip version is ``pip 8.1.2``, python version is ``Python 3.5.1+``

<pre>
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

$ uname -a
Linux 721c971d0d37 4.4.20-moby #1 SMP Thu Sep 15 12:10:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/version
Linux version 4.4.20-moby (root@3934ed318998) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #1 SMP Thu Sep 15 12:10:20 UTC 2016

$ python -V
Python 2.7.12
</pre>

The certificates are signed by an own root CA (private PKI)

**Comment by untergeek** [comment] 2016-10-09 22:09
>```
$ apt-get install -y python3-pip python3-elasticsearch-curator=4.1.2
$ pip3 install -U setuptools
Successfully installed setuptools-28.3.0
```

This is unusual.  I suggested the way to do it was to install the version of setuptools I compiled into a package at the same time as the Curator package, e.g.

```
$ apt-get install -y python3-setuptools python3-elasticsearch-curator
```
I do know that that works, as I have tested it on 16.04 VMs.

It's either that, or install everything via pip:

```
$ apt-get install -y python3-pip
$ pip3 install -U setuptools elasticsearch-curator 
```

Mixing those methods may be the issue.

**Comment by untergeek** [comment] 2016-10-10 14:46
@floragunncom 

Are you using Shield, or some other method to secure Elasticsearch?

**Comment by floragunncom** [comment] 2016-10-10 22:08
``apt-get install -y python3-setuptools python3-elasticsearch-curator`` fails with ``ImportError: No module named 'pkg_resources'``

If i install with
<pre>
pip3 install --upgrade pip
pip3 install -U setuptools
pip3 install -U elasticsearch-curator 
</pre>
then curator failed with

<pre>
 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 94, in perform_request
     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
     chunked=chunked)
   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
     self._validate_conn(conn)
   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 833, in _validate_conn
     conn.connect()
   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 324, in connect
     cert = self.sock.getpeercert()
   File "/usr/lib/python3.5/ssl.py", line 814, in getpeercert
     return self._sslobj.getpeercert(binary_form)
   File "/usr/lib/python3.5/ssl.py", line 591, in getpeercert
     return self._sslobj.peer_certificate(binary_form)
 SystemError: <built-in method peer_certificate of _ssl._SSLSocket object at 0x7efe97dd8270> returned NULL without setting an error

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/dist-packages/curator/utils.py", line 580, in get_client
     check_version(client)
   File "/usr/local/lib/python3.5/dist-packages/curator/utils.py", line 424, in check_version
     version_number = get_version(client)
   File "/usr/local/lib/python3.5/dist-packages/curator/utils.py", line 397, in get_version
     version = client.info()['version']['number']
   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
     return func(*args, params=params, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 220, in info
     return self.transport.perform_request('GET', '/', params=params)
   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 327, in perform_request
     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 105, in perform_request
     raise ConnectionError('N/A', str(e), e)
 elasticsearch.exceptions.ConnectionError: ConnectionError(<built-in method peer_certificate of _ssl._SSLSocket object at 0x7efe97dd8270> returned NULL without setting an error) caused by: SystemError(<built-in method peer_certificate of _ssl._SSLSocket object at 0x7efe97dd8270> returned NULL without setting an error)

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/bin/curator", line 11, in <module>
     load_entry_point('elasticsearch-curator==4.1.2', 'console_scripts', 'curator')()
   File "/usr/local/lib/python3.5/dist-packages/curator/curator.py", line 5, in main
     cli()
   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
     return self.main(*args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
     return callback(*args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/curator/cli.py", line 165, in cli
     client = get_client(**client_args)
   File "/usr/local/lib/python3.5/dist-packages/curator/utils.py", line 587, in get_client
     'Error: {0}'.format(e)
 elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<built-in method peer_certificate of _ssl._SSLSocket object at 0x7efe97dd8270> returned NULL without setting an error) caused by: SystemError(<built-in method peer_certificate of _ssl._SSLSocket object at 0x7efe97dd8270> returned NULL without setting an error)
</pre>

I use https://github.com/floragunncom/search-guard-ssl to secure elasticsearch and its configured i that kind that the client is required to present a client certificate.

 I know this kind of error from when i try to connect via urllib3 directly and i had to call ``urllib3.contrib.pyopenssl.inject_into_urllib3()`` first to make it work. RequestsHttpConnection seems to work out of the box.

**Comment by untergeek** [comment] 2016-10-10 22:20
I couldn't even get Curator 4.1.2 to build via pip3 on my 16.04 install.  It seems that something weird happened with the most recent version of setuptools.  It fails during the wheel build, because the wheel build seems intent on downloading the most recent version of setuptools, regardless of what's installed locally.

That said, with the current binary package (Python 2.7.12 based), I can confirm _part_ of the behavior you saw above with regards to the SNI error:
```
2016-10-10 16:17:11,171 DEBUG              curator.utils             get_client:524  kwargs = {'url_prefix': '', 'aws_secret_key': None, 'http_auth': None, 'certificate': '/home/buh/ca/certs/cacert.pem', 'aws_key': None, 'aws_region': None, 'client_cert': '/home/buh/ca/aaronm-signed.crt', 'hosts': ['steiny.untergeek.net'], 'timeout': 30, 'use_ssl': True, 'master_only': False, 'port': 9200, 'ssl_no_validate': False, 'client_key': '/home/buh/ca/private/aaronm-key.pem'}
2016-10-10 16:17:11,171 DEBUG              curator.utils             get_client:530  Attempting to verify SSL certificate.
2016-10-10 16:17:11,174 DEBUG              curator.utils             get_client:567  "requests_aws4auth" module present, but not used.
/opt/elasticsearch-curator/library.zip/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/opt/elasticsearch-curator/library.zip/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Enter PEM pass phrase:
```
but it still connects in the end:
```
2016-10-10 16:11:28,359 DEBUG              curator.utils          check_version:427  Detected Elasticsearch version 2.4.1
2016-10-10 16:11:28,359 DEBUG                curator.cli                    cli:166  client is <class 'elasticsearch.client.Elasticsearch'>
2016-10-10 16:11:28,359 INFO                 curator.cli                    cli:172  Trying Action ID: 1, "delete_indices": Delete indices older than 15 days (based on index name), for any Year.month.day indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2016-10-10 16:11:28,360 DEBUG                curator.cli         process_action:39   Configuration dictionary: {'action': 'delete_indices', 'description': 'Delete indices older than 15 days (based on index name), for any Year.month.day indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.', 'filters': [{'direction': 'older', 'stats_result': 'min_value', 'filtertype': 'age', 'source': 'name', 'epoch': None, 'timestring': '%Y.%m.%d', 'exclude': False, 'unit_count': 15, 'unit': 'days'}], 'options': {}}
```

So I have an SNI error, even with a cx_Freeze compiled version from Python 2.7.12.

I did a test build of the binary package with Python3 3.5.2 and the error goes away:

```
2016-10-10 16:16:29,321 DEBUG              curator.utils             get_client:524  kwargs = {'master_only': False, 'client_key': '/home/buh/ca/private/aaronm-key.pem', 'timeout': 30, 'client_cert': '/home/buh/ca/aaronm-signed.crt', 'url_prefix': '', 'ssl_no_validate': False, 'hosts': ['steiny.untergeek.net'], 'certificate': '/home/buh/ca/certs/cacert.pem', 'aws_key': None, 'http_auth': None, 'aws_region': None, 'use_ssl': True, 'port': 9200, 'aws_secret_key': None}
2016-10-10 16:16:29,322 DEBUG              curator.utils             get_client:530  Attempting to verify SSL certificate.
2016-10-10 16:16:29,327 DEBUG              curator.utils             get_client:567  "requests_aws4auth" module present, but not used.
Enter PEM pass phrase:
2016-10-10 16:16:32,043 DEBUG              curator.utils          check_version:427  Detected Elasticsearch version 2.4.1
2016-10-10 16:16:32,043 DEBUG                curator.cli                    cli:166  client is <class 'elasticsearch.client.Elasticsearch'>
2016-10-10 16:16:32,043 INFO                 curator.cli                    cli:172  Trying Action ID: 1, "delete_indices": Delete indices older than 15 days (based on index name), for any Year.month.day indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
```

In both cases, the certificate and keys are connecting to Shield just fine, even with the SNI error.  I'm not sure why SearchGuard isn't playing nice.

**Comment by untergeek** [comment] 2016-10-10 22:38
I know this isn't the news you'd like to hear, but if it works for Shield right now, with Curator functional out of the box using SSL + PKI, then I'm satisfied that the base functionality works as expected with the official Elastic plugins, and there is no major bug needing to be addressed.

I'm not opposed to merging a pull request to address your issue, but I will not be writing a fix myself. I can only accept a pull request to merge new functionality so long as it doesn't break any existing behaviors.  It would have to test properly in Python 2 and Python 3 on RHEL/CentOS 6 & 7, and Ubuntu 12.04, 14.04, & 16.04, and work with ES versions 2.x and 5.0.

**Comment by floragunncom** [comment] 2016-10-10 22:41
Did you try Shield with client certificates enforced?
``shield.http.ssl.client.auth: required``

**Comment by untergeek** [comment] 2016-10-10 23:28
Yes.  It works the same as with it set to `optional`.

Change this:
```
#shield.http.ssl.client.auth: optional
shield.http.ssl.client.auth: required
```

Restart, and test again.

Same result:
```
2016-10-10 17:25:25,605 DEBUG              curator.utils             get_client:524  kwargs = {'hosts': ['steiny.untergeek.net'], 'http_auth': None, 'client_key': '/home/buh/ca/private/aaronm-key.pem', 'port': 9200, 'url_prefix': '', 'client_cert': '/home/buh/ca/aaronm-signed.crt', 'master_only': False, 'aws_key': None, 'certificate': '/home/buh/ca/certs/cacert.pem', 'aws_secret_key': None, 'use_ssl': True, 'timeout': 30, 'ssl_no_validate': False, 'aws_region': None}
2016-10-10 17:25:25,605 DEBUG              curator.utils             get_client:530  Attempting to verify SSL certificate.
2016-10-10 17:25:25,610 DEBUG              curator.utils             get_client:567  "requests_aws4auth" module present, but not used.
Enter PEM pass phrase:
2016-10-10 17:25:30,271 DEBUG              curator.utils          check_version:427  Detected Elasticsearch version 2.4.1
2016-10-10 17:25:30,271 DEBUG                curator.cli                    cli:166  client is <class 'elasticsearch.client.Elasticsearch'>
2016-10-10 17:25:30,271 INFO                 curator.cli                    cli:172  Trying Action ID: 1, "delete_indices": Delete indices older than 15 days (based on index name), for any Year.month.day indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
```

**Closed** 2016-10-14 15:20 UTC

**Comment by untergeek** [comment] 2016-10-14 15:21
#783 addresses the situation where older versions of Python lack the necessary libraries for SSL/TLS support. It does not fix Curator's usability with regards to Search Guard SSL
