### ISSUE TITLE
curator using unique ID's in s3 snapshots

### ISSUE THREAD

**Issue by JoeOrtiz** [elastic/curator#856] opened 2016-12-23 17:37 UTC
I don't have this issue on ES 2.0.0 and Curator 4.2.4

But on Curator 4.2.4 and ES 5.1.1 the indexes in S3 when performing a snapshot show up like so:

```
[2016-12-23 17:36:42 UTC]     0B -GxyyecaRmm2VGLpOBK0JQ/
[2016-12-23 17:36:42 UTC]     0B -VhJsbosTrGVg_nswx0Mww/
[2016-12-23 17:36:42 UTC]     0B 0S4qpiOnRpuakvuN9qAWIA/
[2016-12-23 17:36:42 UTC]     0B 1rAMSaO5T4a_1ZcMSSFvxA/
[2016-12-23 17:36:42 UTC]     0B 257WQ6amSsKxjHoAbNvJYg/
[2016-12-23 17:36:42 UTC]     0B 2AC9TFTfQWWLofbInBJYmQ/
[2016-12-23 17:36:42 UTC]     0B 2h5teYKbQPSozrQ2qqAInA/
[2016-12-23 17:36:42 UTC]     0B 2wXGnmLuQVSCOnh5kMzUWQ/
[2016-12-23 17:36:42 UTC]     0B 3HlURfBKS0SOlbfZ1Unndw/
[2016-12-23 17:36:42 UTC]     0B 3kbcim64QWGU0YYB8-na7g/
[2016-12-23 17:36:42 UTC]     0B 3sgU2_QWQxGNth_yIk0Vxw/
[2016-12-23 17:36:42 UTC]     0B 5gDOuNjzSAilMCeANaLSjg/
[2016-12-23 17:36:42 UTC]     0B 5jT3qx0kQN-4mpe28QClmQ/
[2016-12-23 17:36:42 UTC]     0B 6DiArIg3QcW2dxkLVxLC_A/
[2016-12-23 17:36:42 UTC]     0B 6p8hxTOFSGmF68Q413GzXQ/
[2016-12-23 17:36:42 UTC]     0B 6rwEQ5Y6S_e66SyC6dQxEA/
[2016-12-23 17:36:42 UTC]     0B 6vRnqFC8QmGeNndxpEobIQ/
[2016-12-23 17:36:42 UTC]     0B 6yzKwUGARNC3EFgvrk-w9Q/
[2016-12-23 17:36:42 UTC]     0B 70MQin6fRbm1eebtjjjbvw/
[2016-12-23 17:36:42 UTC]     0B 7RkgGFUmQC2ytHSW88o1Tw/
[2016-12-23 17:36:42 UTC]     0B 7TaJeWXXQEquGQHYdp-8yg/
[2016-12-23 17:36:42 UTC]     0B 9BXWaBD1SBuOOEFuFt6xMQ/
[2016-12-23 17:36:42 UTC]     0B 9hP2963NToWpLDbp--yjrg/
[2016-12-23 17:36:42 UTC]     0B A9YlAgK2RvWlF_1XgoZgOw/
[2016-12-23 17:36:42 UTC]     0B AZy5lh6BT4euqkc02cJ00w/
[2016-12-23 17:36:42 UTC]     0B Av4iuUAYTCqJUgqQkczoVg/
[2016-12-23 17:36:42 UTC]     0B B04DdUKZR5W6TlgKuRzl9g/
[2016-12-23 17:36:42 UTC]     0B BD_njYSFSdK5n2zSV5UPRw/
[2016-12-23 17:36:42 UTC]     0B BOZFrWKVQ0iI3Sen90qCeA/
[2016-12-23 17:36:42 UTC]     0B Cr3sA7XOQxSugAWZOZdykA/
[2016-12-23 17:36:42 UTC]     0B CzCVJtm6Rjaag-VSaD90DA/
[2016-12-23 17:36:42 UTC]     0B D1-C3KPaSwiavNmkVQV3Cw/
```

Even the metadata isn't keeping the name tag:

```meta-34Ic09erTwu7nau4pAzflQ.dat```

Although a _/snapshot/s3/_current , it does show the proper names and metadata ID. Is this expected behavior?

**Comment by untergeek** [comment] 2016-12-23 17:42
Probably a duplicate of https://github.com/elastic/curator/issues/828#issuecomment-265589719

**Comment by untergeek** [comment] 2016-12-23 17:42
It will probably be fixed in Curator 5.0, as I believe it's an artifact of using the 2.x API calls to 5.0.

**Comment by reedflinch** [comment] 2017-03-07 20:28
Just wanted to drop a line that I'm also seeing this with Curator 4.2.6 and ES 5.1.2. Thanks for your work on this project!

**Comment by untergeek** [comment] 2017-03-27 21:54
This does not appear to happen with the master branch, or the 5.x branch.  I'd love it if you could test with the 5.x branch and see if it still appears this way on your end.

**Comment by untergeek** [comment] 2017-04-10 17:42
Now that Curator 5.0 is officially released, I hope to hear back on this, officially.

**Comment by untergeek** [comment] 2017-06-06 16:18
The snapshots are supposed to have these unique ids.  This is a feature, not a bug.  This is a change made in elasticsearch.  Indices, too, are not named in the filesystem as before.

**Closed by untergeek** 2017-06-06 16:18 UTC
